---
title: "The Hidden Poor: Solving Time Poverty through Redistribution of Household Production"
format:
  simart-pdf:  
    keep-tex: true  
    fontsize: 11pt
    number-depth: 3
  docx: default
crossref:
  custom:
    - kind: float
      reference-prefix: Table A
      space-before-numbering: false
      key: atbl
      latex-env: atbl
      latex-list-of-description: Appendix Tables
      caption-location: top

author:
    - name: "Fernando Rios-Avila"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504
    - name: "Aashima Sinha"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504
date: today
keywords: "Time Poverty, Income Poverty, Redistribution , household production, care work, gender equality, LIMTIP"
abstract: |
    xxx

bibliography: biblio.bib
---


 # Introduction

 Redistribution of household production has been identified as an important tool to achieve gender equality (Elson  The incorporation of the 3R (recognizition, reduction adn redistribution) strategy as a target in the sustainable development goals, is a testament to the decades of activism and advocacy emphasizing that inequality on this front cannot be justified in the name of “private family matter” rather is a matter of public policy. 
 While redistribution of household production responsibilities from females to males is important intrsinsically for human rights and fairness concerns, it is also instrumental in achieving gender equality in labor market outcomes (Bruyn-Hundt 1996; Elson 2017; Esquivel 2016). Yet, difficult questions remain about public policies and collective actions that would reduce inequality, especially in poorer countries. A limited consensus seems to have emerged regarding the effectiveness of certain policy initiatives (e.g., paid paternity leave). But, many of them are likely to have only limited efficacy in the poorer countries due to their structural features such as the widespread absence of formal wage labor and weak welfare states.
In the case of the US, issues related to lack of public prpovisioning of care infrastructure and services, persistence of childcare deserts, lack of paid parental leave laws among others have gained momentum. 
In 2021, the value of unpaid care work in the U.S. amounted to $600 billion, constituting approximately 2.6% of the GDP (Reinhard et al. 2023). Moreover, like most other countries, we observe gender disparity in sharing  of household work such that women disproportionately shoulder the burden. According to the 2018 American Time Use Survey, among adults aged 15 and older, women on average spent 5.7 hours per day on unpaid household and care work, compared with 3.6 hours for men. In other words, women spent 37 percent more time on unpaid household and care work than men (Hess & Hayes 2020). Additionally, the U.S. falls behind many OECD countries in childcare policies and outcomes, spending only 0.4% of GDP on early childhood education and care (ECEC), compared to the OECD average of 0.8% (OECD 2020). Notably, the U.S. lacks federal laws granting paid parental leave, setting it apart from other OECD nations. Around 51% of the U.S. population resides in childcare deserts, defined as census tracts with more than 50 children under the age of 5 and either no childcare providers or significantly limited options, resulting in a severe shortage of licensed child care slots (Malik et al. (2018)). 
In the above setting, care demand falls onto the households, partculalrly women. This in turn restricts care providers allocation of time to other activities including employment, leisure, socializing and self care. Time-trade off are crucial determines individual's well-being. While some hosuheolds may be able to outsource some of these care needs, other income-constraint hosuehodls may not be able to. In the last two decades, there has been growing interest in studying time and income poverty and in developing their linkages (xx). 

Time constraints that stem from the overlapping domains of paid and unpaid work are of central concern to the debates surrounding economic development and gender equality. In this backdrop, we develop a novel measure of poverty for the 
U.S. that incorporates time deficits, known as the Levy Institute Measure of Time and Income Poverty (LIMTIP). Time deficits due to household production is gaining attention in the U.S given the persisting lack of publicly provided care, affordable child and elderly care, and limited paid parental leave benefits. These time deficits constrain people’s time allocation in a range of activities, in turn affecting their overall well-being, productivity, labor market participation, and earnings. The consequences are particularly serious for women due to the disproportionate burden of household responsibilities they bear, which are closely intertwined with labor market and well-being outcomes. Standard measures of poverty fail to capture hardships caused by time deficits and thereby do not provide a complete picture for effective poverty-alleviation and welfare programs. Understand the incidence of time poverty that individuals face and how that may have implications for the study of poverty, gender equality and overall development is therefore crucial.


# LIMTIP: A New Measure of Time Poverty for the United States

- Describe the LIMTIP measure and how it is constructed: Methods paper
- Brief description of the LIMTIP measure and the Hidden Poor in the US. Small section

Poverty is a multidimensional concept that goes beyond the simple notion of lack of income. In addition to income, poverty can be understood as a lack of access to resources, including time. The LIMTIP is a metric that incorporates in addition to income poverty, aspects of time poverty. Time poverty refers to  a scenarion wherein people may not have any time left after engaging in activities that are essential for taking care of the household, its members, self-care, and paid work. 

As with any other measures of poverty, it is necessary to identify a threshold to determine if given the resources available to a person or household, they should be classified as poor or non-poor. In the case of time, however, thinking about a threshold is less intuitive because all individuals have the same amount of time available to them i.e 24 hours in a day. Instead, the approach used for the construction of the LIMTIP has been to identify the time balance people would potentially face after considering the necessary time spent on essential activities and household responsabilities. In this framework, people with a negative balance are considered time-poor. We express the weekly time balance of individual $i$ in household $j$, $X_{ij}$, as:

$$X_{ij} = 168 - M - \alpha_{ij}R_j-D_{ij}^0(L_{ij}+T_{ij})
$$ {#eq-bal}

where 168 is the number of hours in a week, $M$ is the sum of personal care and non-substitutable household production requirements, $R_j$ is the required time of household production that a family $j$ needs to maintain the household, $\alpha_{ij}$ is the share of individual $i$ in the household production requirements. To account for required time due to working, the @eq-bal also includes $D_{ij}$, a dummy variable that takes a value of 1 if the person is employed and zero otherwise. Thus, for those employed, one also accounts for hours of employment $L_{ij}$ , the hours of commuting $T_{ij}$.

To construct this measure, we need a dataset that contains information on individuals' time use, in addition to standard information required for poverty analysis. The main source of information for time use comes from the American Time Use Survey (ATUS), which only provides information for a single person in the household and a single day. It is necessary to combine the ATUS with the ASEC data to construct a synthetic dataset that contains information on time use for all household members, which will allow us to impute all required variables for @eq-bal.

Using ATUS and ASEC data and utilzing statitical matching we develop income and time poverty estimates for the United States for the years 2005 to 2022. In this policy brief we focus on discussing the LIMTIP estimates for the year 2022(!TBD).


The LIMTIP is finally measured as: 
$$P_{j}^L* = P_{j}^O- p_{j}*X_{j}
$$ {#eq-limtip}

The underlying idea is that if we were to monetize the time deficits of individuals and add those to the offical income poverty thresholds, we get an adjusted poverty line - LIMTIP.
The estimation of LIMTIP helps us calculate the number of hidden poor, i.e time poor indivuals who are left outside the scope of official income poverty estimates. The difference between the LIMTIP measure of poverty and the official poverty estimates give us the number of hidden poor. 

In @fig_trend we present time trend from 2005 to 2023 of time poverty estimates, the offical poverty trend, the LIMTIP poverty trend. We observe that the official poverty estimates shows a slight rising trend between 2005 to 2014 and then starts to decline. The pandemic years show some steep decline from 13.8 % in 2020 to 10% in 2022 before rising back to the pre-pandemic level of around 15%.
When we adjust for time deficits, as expected our LIMTIP estimates shows a higher level of poverty, around 25 percentage points higher . The gap widened during pandemic years.
Moreover, it is notable that time poverty peaked around Great recession and Covid-19 pandemic recession. While time poverty rate has remained more or less stabke until 2019, it fell slightly in 2020 before rising again between 2020 to 2023.
We also observe that in 2022, nearly 33 percent of individuals are hidden poor in 2022. 
Further, in Table xx and yy we present the distribution of individuals and hh respectively across the four-way classification of LIMTIP (time poor and i) for the year 2022.


In the next section, we identify the subsample that can potentially be brought out of poverty. 


# Identifying the Problem
The scope of the redistribution of household production responsibilities in reducing time poverty depends on the living arrangements of individuals. If the time-poor household consists only of one working-age individual, no redistribution is possible. For example, a family of an employed single mother and her young children is an important type of family that is quite vulnerable to time poverty yet falls outside the scope of redistribution. Households with two or more working-age persons can vary in terms of the characteristics relevant to time poverty and redistribution. A household is classified as time-poor if atleatst one working age member is time-poor. A time-poor households in which all working-age members are time-poor represent a case where individual and collective interests may not coincide. In these households, redistribution is possible but ineffective in reducing the household’s time deficit. Hence, redistribution cannot change the household’s status of time or income poverty. A married (cohabitating) couple with young children where both spouses encounter time deficits while managing their jobs and household responsibilities fits this description. However, redistribution can make time deficits less unequal between the time-poor persons in this group of households, even potentially facilitating the transition out of time poverty for some individuals. Greater gender equality in the division of household responsibilities is desirable in this group, too, because gender equality is intrinsically important, irrespective of whether it affects the household’s income or time poverty status.


We specify our problem statement to bring households out of poverty and focus on only those households which can be brought of poverty. For this purpose, we identify the households with atleast one time poor and one time non-poor adult individual for us to redistribute effectively so that the hh can fall out of poverty. This excludes:
i) single individual housheold 
(ii) hosueholds with irreducible time poverty (i.e housheolds where total time surplus falls short of total tme deficit, thereby not allowing for any effective redistribution).
By the same logic we end up identifying households where we can :
(i) Reduce individual time poverty []
(ii) Reduce share of hosueholds experienecing time poverty 

In @fig_idsample xxx

- The problem we need to identify the problem of time-poverty caused by redistribution (or lack thereof) of household production.
- Identify either: how many Time poor individuals live in household with time non-poor adults.
- Or identify the baseline of time poverty if there is full flexibility for time allocation. (Household Deficit consider both time deficits and surpluses)

This would give us a fist look at how much poverty could be alleviated if household production was redistributed.

We could even look at Who are this individuals who are living in time poverty, but that Do not need to. (describe the characteristics of these individuals)

- Added value. This will help us identify those who cannot be helped by redistribution of household production. (even if their incidence changes

- This raises the question. Do we want to analyze redistribution in household that are not time poor?


Next,  we develop three redistribution scenarios wherein we redistribute the share of household production responsibilities among the household’s working-age memebrs while all else remains. In other words, we examine the effects of a new set of values of $\alpha_{ij}$. Redistribution will change the magnitude of the time balanace in @eq-bal and, depending on the extent and direction of the change, may result in a time-poor person becoming time-nonpoor or a time-nonpoor person experiencing time poverty. We focus on the subsample of households for which redistribution is possible and efficient. For example redistributing househodd prod in a hh with atleast one time poor and one time non poor individual along with the constraint that redistribution can take place to adults belonging to 18-64 years. This allows for us to not redistribute household production to children.
 
# Redistribution Scenarios

- Here we would describe the three redistribution scenarios we have developed. This would be "realistic" scenarios. 

- Describe the scenarios and the assumptions behind them.

Intrahousehold redistribution can potentially reduce time deficits. We construct three redistrubution scenarios based on different guiding principles. The extent of the reduction would depend on the principle that we use in distributing household responsibilities among the members. 
First, we use the simple egalitarianism principle that involves an equal division of total household productiom time among all working age members. Second, we redistribute conditional on the available time people have. In the thord scenario, we redsitribute based on the opportunity cost of time for people. 

xxxx
In the next section, we outline the methods used for implementing the principles in our data, with the detailed explanation of some aspects below:


## Distribution Rules for Household Production
Alternative values of $\alpha_{ij}$ indicate how household production requirements, net of the portion met by household members that are not of working age or are physically unable to take on more work, are shared between working-age persons in the household.  Below we discuss the three principles.

### 1. Equal Shares Scenario
The procedure for the equal shares scenario is relatively simple. Recall that the shares of those in the redistribution simulation in this scenario are simply:


 As before, denoting the number of working-age persons in household $j$ as $I^j$, we can express the rule as:

$$\alpha_{ij}^E= 1/I_j*(1-\alpha_{j}^{nw'})
$$ {#eq-r1}

We need to count how many people are in the redistribution simulation in each household and then assign them the appropriate fraction (1 for households with one person in the simulation, 1⁄2 for households with two people in the simulation, and so on) and apply that fraction to the redistributable share of required household production time. 


### 2. Time Available Scenario (WIP editing)
The time available scenario is based on equity such that the redistrubted shares are based on the time that is available after setting aside the time for personal maintenance requirements and income generation. In other words, the  household members should split up the required household production time based on the time each one has available, i.e based on an equity criteria. The time available ($Z_{ij}$)) is defined as the time left over after the minimum personal maintenance and time spent on income generation (including commuting time) have been subtracted from the total weekly hours. To calculate the shares for each individual based on this principle, we first calculate the time available for each individual, then add up the total among the household for those individuals that have positive time available. We then divide each individual’s time available by the total and apply that fraction to the redistributable share of household production time. For those individuals that have negative time available we set their shares to zero in this simulation.






### 3. Opportunity costs

The third possibility is based on the idea of opportunity costs along marginalist lines. The sharing rule depends on the relative actual (potential) wage. For example, if there are only two working-age adults, say husband and wife, and if the husband’s wage is twice as much as the wife, the wife’s share would be two-thirds and the husband’s share would be one-third. We use the actual or shadow wage for the employed and the potential wage for the nonemployed.
Redistribution takes place based on the following equation:



 First, we imputed wages for all of those not currently working for pay. In order to do this, we used a two-stage Heckman selection model (Heckman 1979), also known as the Heckit procedure, which we outline below. Once done, we used the imputed wages of those that are not currently working for pay and the actual wages of those that are working to divide up the redistributable share of required household production:


$$\alpha_{ij}^O= (1/{I_j-1})*(1-w_{ij}/w_{ij} ) (1-\alpha_{j}^{nw'})
$$ {#eq-r3}


As the share of required household production needs to be inversely proportional to the individual’s share of the sum of wages, we subtract their share of this sum from one. To ensure that the resulting shares sum up to unity, we divide by the number of individuals in the simulation minus one. We then apply this share to the redistributable share of required household production as in previous steps.
In order to impute wages for those not currently employed for wages, we first impute the likeliest industry and occupation for each individual using a multinomial probit procedure. Industry and occupation are regressed on age, age squared, sex, race, education, and geographic region on all those in the working age population (18-64). The likelihood for each industry and occupation is then predicted for everyone, using the results of the multinomial probit. Then each individual not currently working for wages is assigned the industry and occupation corresponding to the xxxx/ largest predicted likelihoods for that individual.

Next, we move on to the first stage of the Heckit procedure, a probit estimation of a dummy variable for being employed in wage work (paid):

$$P(paid=1|X)=F(X* \beta)
$$ {#eq-probit}

where F is the cumulative density function of a normal distribution. The vector of explanatory variables, 𝑋, comprises the individual’s age, sex, race, disability, number of kids across age groups (0 to 5, 6 to 14, 15-17), presence of spouse and spouse's age, education and employment status education. The regression is run on the universe of all eligible adults separately by age (divided into four categories: 18 to 30 years old; 31 to 45 years old; and 46 to 64 years old) and sex. The Mills ratio, 𝜆, is calculated for all individuals using the results of the first stage regression:



where 𝑓 and 𝐹 are, respectively, the probability and cumulative density function of a normal distribution, and 𝛽􏱞 is the vector of estimated coefficients from the probit model.
The second stage is an ordinary least squares (OLS) estimate of the log of hourly wage:


$$lnw= (\gamma_2*Z^w) + (\theta_2 * \lamda) + 

This regression is run only on those that are actually employed for pay (!FRA). The vector of explanatory variables, [], includes age, sex, race, education, geographical region, disability, industry, occupation, presence of spouse, spouse's employment status, and, finally, λ, the Mills ratio calculated in the first stage. Inclusion of the Mills ratio corrects for the selection bias induced by limiting the regression to those in paid employment. The imputed log of wage is predicted for those not working for wages from the results of the regression, with industry and occupation replaced by the industries and occupations assigned in the previous step.


Describe our procedue : 2 stages


We simulate each of these principles of redistribution and recalculate individual and household time and income poverty using the LIMTP framework described above. 

##Next, we provide an assessment of the different principles in terms of how far they improve the position of women and how much such improvements are congruent with the betterment of the economic well-being of their families. In the subsequent section, we compare and contrast the joint distribution of time and income poverty among families and individuals that would result from each principle.

# Results

- Compare the time poverty changes on those identified earlier. 
 
- Moreover, we examine the changes by sex, employment status, presence of children
in the household. 
- Perhaps Start with a global analysis (without Specific groups)
- then Analyze the case for Specific groups

Perhaps provide more emphasis on Some of the groups (gender, the employed, parents?)

## Gender Disparity in the Incidence of Time Deficits
In this section we present the time deficits and LIMTIP poverty estimates by gender. We consider other characteritics of indivdiuals and hh such that employment status and nuber of children, factors which affect time availability. 

Evidence indicates that negative time balance values (i.e., time deficits) occur mostly among employed persons, we look at the heterogenous differences by presentinf limtip estimates by employment status and sex in @tbl_ws. We observe that xxx



Further, presence of children would demand more caregiving hours thereby putting a pressure on time available, particulalrly for employed couples or single memebr hosuehodls. 
Add table by sex and children for limtip and discuss results.

##Gender and race Disparity in the  Incidence of Time Deficits
Finally, in the case of the US, race inequality holds significance. In Table xx we present the 


# Policy implications

# Conclusion
