---
title: "Redistribution and Time Poverty: Balancing Responsibilities in Couple Households"
format:
  simart-pdf:  
    keep-tex: true  
    fontsize: 11pt
    number-depth: 3
  docx: default
author:
    - name: "Fernando Rios-Avila"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504
    - name: "Aashima Sinha"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504
    
date: today
keywords: "Time Poverty, Income Poverty, Redistribution, household production, care work, gender equality, LIMTIP"
abstract: |
    This policy brief examines how redistributing household production responsibilities could reduce time poverty among married U.S. couples. Using the Levy Institute Measure of Time and Income Poverty (LIMTIP), we analyze three scenarios based on equality, equity, and opportunity cost principles. Our findings show that redistribution could effectively reduce time poverty in households where time surplus exceeds deficits, with the equity-based approach proving most successful. However, redistribution has limited impact when all household members are already time-poor. The effectiveness varies across household structures, suggesting targeted approaches may work better than universal solutions.

bibliography:
  - publications.bib
  - biblio.bib
  - references.bib
---

# Introduction

<!-- Words ~1500 -->

Redistribution of household production, which includes unpaid caregiving and domestic chores, has been identified as an important tool to achieve gender equality. The United Nations Sustainable Development Goal 5, Target 5.4, has incorporated the recognition, reduction, and redistribution of unpaid work staretgy, popularly known as the 3R strategy. This is a testament to decades of activism and advocacy emphasizing that gender inequality on this front cannot be simply justified as a "private family matter", but rather be considered a matter of public policy. Redistribution can take place from households to the public and/or private spheres, as well as among household members. While all household members should share household work, evidence shows that it is disproportionately undertaken by girls and women globally [@addati2018].

Redistribution of household production responsibilities from women to men is important intrinsically for human rights and fairness concerns; it is also instrumental in achieving gender equality in labor market outcomes [@hundt1996; @elson2017; @valeria2016]. Studies have demonstrated that gender gaps in the workforce and the unequal sharing of household responsibilities can severely impede economic growth and development [@elson2009; @berik2009; @duflo2012]. Yet, public policies and collective actions have been less than adequate, especially in poorer countries due to constrained fiscal capacity, widespread absence of formal wage labor, and weak welfare states. Moreover, in patriarchal contexts, cultural barriers also restrict redistribution of household production among their members, or redistribution between the public and private spheres. While in some developed countries such as Norway and Sweden, public policies have been able to promote gender-equitable sharing of household production, such as paid paternity and maternity leaves, they have attained limited attention and success in other countries.

The U.S. is not an exception. Issues related to lack of public provisioning of care infrastructure and services, widespread existence of childcare deserts, and lack of paid parental leave laws, among others, have drawn attention. In 2021, the value of unpaid household work in the U.S. amounted to \$600 billion, constituting approximately 2.6% of the GDP [@rein2023]. Moreover, like most other countries, we observe gender disparity in sharing of household work,  with women being in charge of a disproportionately larger share of the burden. According to the 2018 American Time Use Survey, among adults aged 15 and older, women on average spent 5.7 hours per day on unpaid household and care work, compared with 3.6 hours for men. In other words, women spent 37 percent more time on unpaid household and care work than men [@hess2020]. 

<!--
lets leave this for now
The disparity is more significant between married men and married women xxxx(TBD) and also in households where children are present. -->

Unfortunately, the U.S. also falls behind in other dimensions of this problem. Compared to other OECD countries, the U.S lacks of effective childcare policies, spending only 0.4% of GDP on early childhood education and care (ECEC), compared to the OECD average of 0.8% [@oecd2020]. The U.S. also lacks federal laws granting paid parental leave, setting it apart from other OECD nations. Around 51% of the U.S. population resides in childcare deserts, defined as census tracts with more than 50 children under the age of 5 and either no childcare providers or significantly limited options, resulting in a severe shortage of licensed child care slots [@malik2018].

## What does this means for time poverty?

The lack of public provisioning of care infrastructure and services, and the disproportionate burden of household production on women, has implications for time poverty, both at the individual and the household/family level. 

But what should we understand as time poverty?

Over the last decades, the Levy Economic Institute has been at the forefront of recognizing the importance of time for understanding income and poverty dynamics [@zacharias2011]. As part of this work, they developed a new measure of poverty that incorporates the dimension of time into traditional poverty measures: The Levy Institute Measure of Time and Income Poverty (LIMTIP for short). This measure uses synthetic data in order to incorporate the value of time, or more specifically the amount of resources required to outsource the responsibilities that cannot be covered by the household members, into traditional measures of poverty thresholds. By incorporating this dimension, the LIMTIP not only provides a more comprehensive understanding of poverty but also allows for the identification of the hidden poor, i.e., individuals whose families do not have enough monetary resources to accommodate for the time deficits they face [@zacharias2021; @masterson2012; @Antonopoulos2017; @zacharias2012; @zacharias2014; @zacharias2018].

In priciple, individual time poverty refers to the lack of time available for individuals to engage in activities that are essential for taking care of the household, its members, self-care, and paid work. This on itself its a difficult concept to grasp, because every individual has different responsibilities and needs, and thus, different time constraints. To formalize this definition, LIMTIP assumes that all individuals have the same time constraints (168 hours per week) that they need to allocate among household production, personal maintenance, and paid work. Some of this components are identified based on peoples decisions (ie Time spend on Paid work), but others are assumed to have some minimum time requirements, such as the case for household production and personal maintenance. If the responsabilities of individual exceeds the 168 hours per week, 

To identify time poverty at the household level, LIMTIP imposes the assumption that individuals are unable or unwilling to help those with time deficits. Thus, even if a single individual struggles to meet their responsibilities, the whole family is considered to be living under time poverty. In this framework, as pointed out in @policybrief_USLIMTIP, it is not uncommon to see households with a mixture of time availability (i.e deficts and surpluses) among its members. In fact, just over 20% of the working-age population are not time-poor but live in a household where at least one person lives under time poverty. Because the LIMTIP assumes household production is the only component that can be shared among household members, this mixture of time availability among household members suggests that not everyone is pulling their weight in terms of household production.

In spite of the growing recognition of the importance of time constraints and the responsibility of household production, the issue of time poverty has received limited attention in the U.S., partially due to data availability constraints.

<!-- 20% for what year?-->
What does this means for time Poverty in the U.S.?

While most of the earlier work on LIMTIP has focused on the analysis of time poverty in developing countries [@masterson2012; @zacharias2018; @masterspm2022], recent work has extended the measure to the U.S. [@zacharias2024a; @policybrief_USLIMTIP].[^1] Similar to earlier work, one of the findings of @policybrief_USLIMTIP is that a large share of the population experiences some level of time poverty, which translates into a significant share of households who are ***hidden poor***, thus not captured by the official income poverty measure. In this policy brief, we suggest that a significant share of time-poor individuals and households could potentially exit time poverty if household production responsibilities were to be redistributed among its members (similar to @zacharias2021).

[^1]: This is in addition to the work done for the Levy Institute Measure of Economic Well-Being (LIMEW).

Following @policybrief_USLIMTIP, this policy brief explores the potential impacts of redistribution further. Using the new estimates for LIMTIP for the U.S., we provide insights into how redistributing household production can reduce the incidence of poverty not only for individuals but also of the households they live in. Specifically, given the marked responsibilities gap between men and women, we focus on analyzing the impact of redistribution among married couples. To do this, we consider three redistribution scenarios based on equality, equity, and opportunity cost principles and assess the impact of redistribution on time poverty of working-age (18-64 years) household members who are part of a heterosexual couple. Further, we present the impacts for different household types, household structures (presence of young children and other members), poverty groups and employment status. 

<!--

Im thinking taking this out for the Policy brief, as this was lighly explained earlier

In the next section, we start by briefly describing the LIMTIP measure and our estimates for the US. We then move on to identifying the different types of households experiencing time poverty, the redistribution scenarios, followed by results and policy implications.

# LIMTIP: A New Measure of Time Poverty for the United States


-->

# How to Measure Time Poverty?: The Levy Institute Measure of Time and Income Poverty

Poverty is a multidimensional concept that goes beyond the simple notion of lack of income. In addition to income, poverty can be understood as a lack of access to resources, including time. The LIMTIP is a metric that, in addition to income poverty, incorporates aspects of time poverty that better capture the control households have over their resources. 

As described in @policybrief_USLIMTIP and @wp_qmatch, the LIMTIP is built using a synthetic dataset that combines information from the American Time Use Survey (ATUS) and the Annual Social and Economic Supplements (ASEC) of the Current Population Survey (CPS). Using this synthetic data, and considering a period of reference, such as hours per week or year, we identify the amount of time individuals would have left ($X_{ij}$) after engaging in required activities for taking care of their share of responsibilities ($\alpha_{ij}$) in household production ($R_j$), personal maintenance ($M$), and paid work (commuting $T_{ij}$ and time spent at work $L_{ij}$).[^ The minimum time required for each of the components in @eq-bal are estimated using a mixture of assumptions, the synthetic dataset, and the ATUS dataset (see @wp_qmatch for details)]. 

$$X_{ij} = 168 - M - \alpha_{ij}R_j-D_{ij}(L_{ij}+T_{ij})
$$ {#eq-bal}

Based on @eq-bal, an individual is classified as time poor if they have a negative time balance.

At the household level, however, we assume that individuals with time surpluses are unable take up extra  responsibilities from those with time deficits. In this framework, a household is considered to be time-poor as long as there is at least one person with a time deficit living in the household.[^2] Thus, as stated in @eq-hbal, the household time deficit is calculated as the sum of all individual time deficits in the household, ignoring any time surpluses that may exist.

[^2]: To identify time poverty status, we only consider the time deficits of household members age 18 or older.

$$X_{j} = \sum_{i=1}^{I_j} \min(X_{ij},0)
$$ {#eq-hbal}

Once household time deficits $X_{j}$ are identified, the official income poverty thresholds is adjusted to account for the monetized value of the time deficits. For the U.S. case, we use a three-year average hourly wage for the industry private households obtained from Merged Outgoing Rotation Groups (MORG) to value the household time deficit. This value represents the amount of income that may be required to outsource some of the time responsibilities and eliminate time poverty. The adjusted poverty line is then calculated as:

$$Z_{j}^{adj} = Z_{j} + 52*P* |X_{j}|
$$ {#eq-limtip}

where $P$ is the price we use to give a monetary value to the time deficits the household ${j}$ faces, $Z_{j}$ is the official poverty line (SPM Poverty line), and $Z_{j}^{adj}$ is the adjusted poverty line. Intuitively, households that are not time-poor will not change status compared to the official poverty estimates. However, households that are time-poor could have their poverty status change if, after considering the adjusted poverty line, they fall below it. This group of households is considered to be the hidden poor.

While there is something to learn from analyzing the impact of the redistribution scenarios across the whole  population, we will concentrate only on time poor households, as the goal is to evaluate the potential of redistribution to lift individuals and households out of time poverty. Furthermore, we will focus only on married couples, where both partners are working-age, non-disabled individuals, to explore the impact of redistribution on the gender gap.

# Where we are: Time Poverty in the United States

<!-- Words ~1500 -->

Between 2015 and 2019 in the U.S., under LIMTIP definition, an average of 35.0% of all households had at least one member who was time poor. If we restrict this to households with a married couple, this share increases to 36.1%, providing a glimpse of the higher prevalence of time poverty among married couples. This last group consitutes the focus of our analysis.  

Within these time poor housheolds, 52% of the married couples may be classified as time poor, with only 7.8% of other members in the household experiencing time poverty. From this share of time poor married couples, only  44% married of men is experiencing time poverty compared to 61% among married women. 
<!-- The shares of required hours of household production reflects gender disparity in sharing of hh work and  it has stayed more or less stagnant during this period (add a figure 2015-19 srhp by sex). In Figures 1 and 2, we present the shares of housheold production and time defeicits experienced by married men and women.
-->

But who are the couples in this time poor households? 

@tbl-stat provides an overview of the characteristics of the households where these couples live. The first type of classification we consider is one that classifies households in regards to their potential to exit time poverty via redistribution. We consider three types of households:

- Households where everyone is time poor, thus redistribuion cannot eliminate time poverty for the household.
- Households where there is at least one non-time poor individual, but its insufficient to eliminate time poverty for the household.
- and, Households where the total time surplus is greater than the total time deficit, thus redistribution can eliminate time poverty for all members in the household.

Overall, 5.2% of couples live in a household where all members are time poor, but 76% could potentially leave time poverty if household production responsibilities were perfectly redistributed. Over half of the couples have a young child living with them (56%) and 25% have other members in the household. In terms of employment status, the vast majority of working-age individuals are employed, with 97% of husbands and 91% of wives are working. This is not surprising, as discussed in @policybrief_USLIMTIP, for most individuals, time poverty is driven by the need to work. 

But what about other characteristics? 

As shown in @tbl-stat, household struture is a critical factor for understanding if redistribution has the potential to reducing time poverty. Household with young children have the lowest chance to exit time poverty (65.5%), compared to other groups. In contrast, the presence of other age-able members in household drastically increases those chances (97.3%).  This is not surprising. The presence of young children increases the time demands on the child care activities, as well as overall household activities due to larger size. On the other hand, the presence of a fall back person for the couple greatly increases the potential of redistribution, because of of this "other-members" do not typically experience time constrains. 

A third pattern observed relates to wife employment status. Families where wives are not currently working show higher potential for time redistribution reducing time poverty. However, this is also observed alongside two other characteristics of these families: they tend to have young children, while also showing a larger proportion of additional household members present.


<!--- Further, in Table xx we present the four-way classification of limtip estimates for individuals. We find that xx % women experience double poverty: income poor and time poor. Given these time poverty outcomes, we investigate the impact of redistribution of household production work among all eligible members in time poor housheolds (18-64 and abled). Our focus is on married couples and we examine if redistribution between them and to other hh members can reduce time poverty. 
Moroever, 5.6% of households are hidden poor, i.e those who are not classified poor based on official poverty estimates but are poor based on LIMTIP estimation. We finally explore the potential of redistribution in lifting households out of poverty and reducing the share of hidden poor. 
-->
:::{#tbl-stat tab-pos="!H" }

\resizebox{\textwidth}{!}{%
{{< include table/tb1.tex >}}
}

Summary Statistics Population

:::

<!--
# Household classification

Households can vary in  terms of the presence of time poor an dtime non-poor members and in terms of the total time deficit and surplus.  Members with time surpluses could take on more household responsibilities, reducing the burden of those with time deficits, and potentially lifting the household out of poverty.  Even if the household remains time-poor, redistribution could still make the time deficits more equal among the household members, particulalry balancing the share between men and women.

We fisrt identify the households where redistribution is possible. Specifically, we exclude from the analysis households that are not time-poor, because the goal of the current analysis is to evaluate the potential of redistribution to lift individuals and households out of time poverty while reducing the gender time-poverty gaps. While non-time poor households could potentially benefit from redistribution, reducing the gaps of time surpluses among household members and/or resulting in more gender-equitable sharing of household work, this is beyond the current scope of this policy brief.

While we allow for redistribution to happen across all working-age (18-64 years) and non-disabled household members (we call this group the elgible sample), our main focus is on analyzing the impact of redistribution between men and women. Thus, we will concentrate on exploring the impact of redistribution on heterosexual couples, where both partners are working-age, non-disabled individuals.

Under these considerations, we use an adaptation of the household classification proposed in @zacharias2021, with two main differences. First, we do not differentiate cases where, as described in @zacharias2021, time poverty is driven by employment. Second, for the household classification, we exclude the disabled when counting the number of members for whom redistribution is possible within a household. Thus, a "single" household refers to a household (SPM unit) where there is only 1 working-age, non-disabled household member. Under these considerations, @tbl-class provides the household classification used for the analysis.

:::{#tbl-class tbl-pos="H"}

| Household Type | Share | Description |
|-----|---|--------------|
| Non-Time Poor | 61.3% | Individuals living in households where no one is time-poor. |
| Single Person Elig | 5.1% | The household has only one working-age, non-disabled individual. Redistribution is not possible. |
| HH Type I | 1.4% | All members in the household are time-poor. Household poverty cannot be eliminated, but individual time poverty could change. |
| HH Type II | 5.2% | There is at least one non-time poor individual living in the household. Household poverty cannot be eliminated because total household time surplus is less than total household time deficit, however individual time poverty can be reduced. |
| HH Type III | 27.0% | There is at least one non-time poor individual living in the household. Household poverty can be eliminated because total household time surplus is greater than total housheold time deficit.|

Household Classification for Redistribution Analysis

:::

Across all these households, we will concentrate only on Households Type I, II and III, since redistribution could modify the time poverty status of individuals or households in these three categories. 

 In @tbl-stat we present an overview of the sample distribution, i.e share of individuals by hosuehold types, characteristics and employment status of husband and wife (check with FRA)

-->

# Where we are going: Redistribution Scenarios

The idea of redistribution of household production responsibilities follows the principle that everyone in a household should be able to carry out their **fair** share of household work. But what constitutes a fair share? While one could construct many rules and strategies to redistribute household responsabilities within a household, we consider three  principles that could guide the redistribution of household production responsibilities among eligible household members.

For the implementation of these scenarios, we consider that all other elements in @eq-bal remain constant with the exception of $\alpha_{ij}$, which is the share of household production time that each individual $i$ in Household $j$ takes on. The goal is to simulate different $\alpha_{ij}$ based on each redistribution scenario, but mantaining the total share of work done by the eligible household members (all members 18-64). This approach imposes the implicit assumption that all household members are equally efficient at taking care of the household responsibilities. 

<!--First, we use the simple egalitarianism principle that involves an equal division of total household production time among all working-age members. Second, we redistribute responsibilities based on the time available to household members. In the third scenario, redistribution is guided based on the principle of opportunity cost of time, where those with higher wages (higher opportunity cost of time) are assigned less household production time.

For all scenarios, we only consider the redistribution of required household production activities $R_j$ net of the portion met by household members that are either disabled or are not part of the working-age population. Thus, the goal is to simulate different $\alpha_{ij}$ values, which represent the share of required household production time that each household member takes on. We also impose the assumption that all household members are equally efficient at taking care of the household responsibilities. We outline the methods used for implementing the scenarios below.
-->

## Scenario 1: Equal Shares

The first scenario considers the impact of redistributing household production such that all responsabilities are equally distributed across all eligible household members. 

$$\alpha_{ij}^E= \frac{1}{I_j}*(1-\alpha_{j}^{nw})
$$ {#eq-r1}

where $\alpha_{ij}^E$ represents the redistributed share of individual $i$; $I^j$ is the number of working-age persons in household $j$ and $\alpha_{j}^{nw}$ represents the total share of all non-working age household members. While this principle aligns with the idea of equality, it overlooks time equity by redistributing tasks without taking into consideration the time available to individuals.

## Scenario 2: Time Available

The time available scenario is based on the principles of equity. In contrast with Scenario 1, this one suggests that household responsibilities could be redistributed relative to the available time individuals may have after setting aside the time for personal maintenance requirements, and income generation ($Z_{ij}=168-M-D_{ij}(L_{ij}+T_{ij})$).

To implement this, we first calculate the time available ($Z_{ij}$) for each individual and recalculate the shares $\alpha_{ij}^A$ using the ratio of time available to the total time available among working-age members. For individuals that do not have any time available ($Z_{ij}<0$), we set it at zero. This ensures that people who already suffer from time poverty are not assigned further tasks within the household. The new share is defined as:

$$
\begin{aligned}
Z_{ij} &=\max{\Big(168-M-D_{ij}(L_{ij}+T_{ij}-E_{ij}(S_{ij}),0\Big)} \\
\alpha_{ij}^A &= \frac{Z_{ij}}{\sum Z_{ij}} (1-\alpha_{j}^{nw})
\end{aligned}
$$ {#eq-r2}

Because there are individuals (young adults) who may still be in school, the standard definition of $Z_{ij}$ may not capture their true time availability. To address this, if an individual is going to school, we subtracts from their available time ($Z_{ij}$) the average number of hours people spend in education activities per week ($S_{ij}$). This correction does not affect the time balance used for the identification of the time poor, only the estimation of time available and the adjusted shares $\alpha_{ij}^A$. 

## Scenario 3: Opportunity Cost

The third possibility is based on the idea of opportunity costs along marginalist lines. The sharing rule depends on the earning potentials of individuals, such that individuals with higher potential wages are assigned a lower share of household production time. In principle, this would encourage the most productive members of the household to spend more time in paid work, while those with lower earning potentials would take on more household production responsibilities. However, because we do not implement any changes in the time spend on paid work, we could also interpret this scenario as a bargaining case where members with the highest potential earnings are able to negotiate a lower share of household production time.

To implement this scenario, we need to calculate the inverse of the wage of each individual $rw_{ij}$,  and then calculate the share of household production time as follows:

$$\begin{aligned}
rw_{ij} &= \frac{1}{w_{ij}}, \ 
\alpha_{ij}^O &= \frac{rw_{ij}}{\sum rw_{ij}} (1-\alpha_{j}^{nw})
\end{aligned}
$$ {#eq-r3}

where $w_{ij}$ is the wage of individual $i$.

Because wage data is not observed for all household members, we use potential/predicted wages for all working-age household members, based on a two step procedure. First, we predict the occupation and industry likelihood for  non-working individuals, and second, we model and predict wages for all household members using a method (heckman selection - @heckman1979) that accounts why some people choose not to work in the first place (self-selection). These predicted wages serve as our measure of how valuable each person's time is. 

# Impact of Redistribution

<!-- Words ~3500 -->

We start by looking at the impact on time poverty. @tbl-tb2 Panel 1 presents the share of married men and women experiencing time poverty. As expected more married women experience time poverty compared to married men (66% vs. 44%).  With redistribution, time poverty can be reduced for married men and married women across all three scenarios, and by a greater margin for women compared to men. This in turn reduces gender disparity for couples. In other words, there is potential to redistribute household production away from couples to other members in the household, improving the well-being of working age married couples. 

In rows 2 and 3 of @tbl-tb2, we present the transition rates i.e entry to and exit from time poverty respectively. Those who are non-time poor in the baseline, some of them enters time poverty in all three scenarios, with more married men entering poverty compared to women except for in scenario 3, where 16 % women became time poor compared to 13.7% men.
Looking at the transition out of time poverty for those who were time poor in the baseline, we find that more women exited time poverty compared to men. For example, in Scenario 1, 42% men exited poverty compared to 75% women, whereas in scenario 2, 70 % men exited compared to 60 % women and in Scenario 3, the exit rates were similar for both men and women at about 60 %.

We next move on to examining time poverty rates and transition rates by household types. The classifocation of households based on the presence of time poor and time-non poor individuals and on total time deficit in relation to time surplus are critical factors driving if redistribution can effectively reduce time poverty in a gender-equitable manner.  In Panel 2 of @tbl-tb2, we present the poverty rates by household type. 
Clearly household type III where there is a mix of time poor and time non poor individuals such that the total surplus outweighs the total time deficit, redistribution is most effective, particularly in scenario 2. While there is no way to make a time poor housheold time non-poor where all members are time poor, there is potential to rachieve greater gender-equitable sharing. 


:::{#tbl-tb2 tab-pos="H" }

{{< include table/tb2.tex >}}


Time Poverty and Transition Rates

:::

Perhaps add a table with all changes in time poverty for each scenario and sub groups. Or do 3 , one for each scenario.

We now look at how these time poverty rates changes by household structure. In @tbl-tb3, we present the time poverty rates by presence of children and presence of other members, both of which are critical drivers of couples’ time poverty incidence. Presence of young household 
children would demand more time to be spent on hh production, while presence of other members can off shoulder some of the hh production work from couples. While presence of children is expected to increase time poverty the latter is expected to decrease time poverty for couples. At the baseline 63% women experience time poverty compared to 44 % men when children are present, and in absence of children, time poverty is similar for men 43% and lower for women at 59%. In both cases share of time poor women is greater. With redistribution, time poverty reduces among married women by a greater margin compared to married men.

Moreover, when other members are present in the hh time poverty is lower compared to when no other member is present. All three-redistribution scenario reduces time poverty, particularly being more effective in scenario 2 and when other members are present.


:::{#tbl-tb3 tab-pos="H" }

{{< include table/tb3.tex >}}


Time Poverty by Household Structure

:::

Adjusted Income Poverty
In @tbl-tb4, we look at the time poverty rate by poverty groups and employment/ earning status of wife. We find that poverty rates are higher among married women compared to married men across all poverty groups. Gender disparity is lowest among below poverty group and increases for income-poverty ratio groups 1-2 % and 2-4% bands before declining for over 4% band.  
Redistribution across all three scenarios reduces time poverty, more so for women and most effectively in scenario 1 followed by scenarios 2 and 3. 

In Panel 2 of @tbl-tb4, interestingly we find that when wife is working time poverty among men is much lower compared to women (40% vs. 66%).  With redistribution , time poverty decrease for both, thereby also reducing gender disparity between couples, except for in scenario 3 where even after redistribution 35% women experience time poverty compared to 24% men. This in turn indicates the vicious cycle exerted by labor market inequality reflected in earnings which then translates into assigning greater share of household production to women given that they earn lower wages, which then also affect their labor market participation and occupational segregation. 


:::{#tbl-tb4 tab-pos="H" }


{{< include table/tb4.tex >}}


Time Poverty by Income

:::

Statistics on the hidden poor
Finally, in @tbl-tb5, we look at share of hidden poor, i.e share of housheolds who are not counted as poor according to the official poverty line but are classified as poor based on LIMTIP calculations because of individuals’ time poverty. At the baseline, 4.7 % hh are hidden poor. With redistribution we can decrease the share of hidden poor and make them visible in poverty alleviation programs. Scenario 2 is most effective in reducing the share of hidden poor. When we look at the share of hidden poor by household types, we find that that the scope of reducing hidden poor is negligible in scenario 1 where everyone is time poor and greatest in scenario 3 where time surplus exceeds time deficits, giving room for more effective redistribution and to the extent of lifiting housheolds out of poverty. Moreover, scenario 2 is the most effective in reducing the share of hidden poor. 
Next, we look at the share of hidden poor if children are present. Hidden poverty rate is higher when children are present compared to in the absence of children (6.6% vs. 2.5%). This aligns with higher time poverty rates for married couple with children. These finding are crucial indicators of the need for publicly provided childcare services that can relieve households of some of these responsibilities and reducing the incidence of time-adjusted income poverty. We also find that intra-hh redistribution can be effective in reducing hidden poverty , particlulary for hosueholds with children and in scenario 2. 

:::{#tbl-tb5 tab-pos="H" }

{{< include table/tb5.tex >}}
 

Hidden Poor by Characteristics

:::


# Policy Implications: Opportunities and Challenges

<!-- Words ~2000 -->

Redistribution can reduce time poverty, but only so much

Which is more effective? Are the results consistent with expectations?

What about based on household characteristics?


# Conclusion/recommendations

<!-- Words ~1500 -->

This policy brief has examined the potential of redistributing household production responsibilities to alleviate time poverty in the United States. Using the Levy Institute Measure of Time and Income Poverty (LIMTIP), we have shown that time poverty is a significant issue affecting 38.7% of individuals living in time-poor households. Our analysis of three redistribution scenarios - based on equality, equity, and opportunity cost principles - reveals that such redistributions can significantly reduce time poverty, particularly in households where time surpluses exceed time deficits.

These findings underscore the importance of considering time poverty in poverty alleviation efforts. They also highlight the potential of intra-household redistribution as a policy tool to promote gender equality and improve overall household well-being. However, the varying effects across household types, hosuheold structures, poverty groups and employment status of wives, along with variations across redistribution scenarios suggest that a one-size-fits-all approach may not be optimal and a targetted tailored approach is needed. 

In conclusion, while redistribution of household production is promising in alleviating time poverty, and the hidden poor, it should be considered as part of strategies that also addresses societal and structural factors that contribute to time and income poverty.



