---
title: "Redistribution and Time Poverty: Balancing Responsibilities in Couple Households"
format:
  simart-pdf:  
    keep-tex: true  
    fontsize: 11pt
    number-depth: 3
  docx: default
author:
    - name: "Fernando Rios-Avila"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504
    - name: "Aashima Sinha"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504
    
date: today
keywords: "Time Poverty, Income Poverty, Redistribution, household production, care work, gender equality, LIMTIP"
abstract: |
    This policy brief examines how redistributing household production responsibilities could reduce time poverty among married U.S. couples. Using the Levy Institute Measure of Time and Income Poverty (LIMTIP), we analyze three scenarios based on equality, equity, and opportunity cost principles. Our findings show that redistribution could effectively reduce time poverty in households where time surplus exceeds deficits, with the equity-based approach proving most successful. However, redistribution has limited impact when all household members are already time-poor. The effectiveness varies across household structures, suggesting targeted approaches may work better than universal solutions.

bibliography:
  - publications.bib
  - biblio.bib
  - references.bib
---

# Introduction

<!-- Words ~1500 -->

Redistribution of household production, which includes unpaid caregiving and domestic chores, has been identified as an important tool to achieve gender equality.
The United Nations Sustainable Development Goal 5, Target 5.4, has incorporated the recognition, reduction, and redistribution of unpaid work strategy, popularly known as the 3R strategy.
This is a testament to decades of activism and advocacy emphasizing that gender inequality on this front cannot be simply justified as a "private family matter", but rather be considered a matter of public policy.
Redistribution can take place from households to the public and/or private spheres, as well as among household members.
While all household members should share household work, evidence shows that it is disproportionately undertaken by girls and women globally [@addati2018].

Redistribution of household production responsibilities from women to men is important intrinsically for human rights and fairness concerns; it is also instrumental in achieving gender equality in labor market outcomes [@hundt1996; @elson2017; @valeria2016].
Studies have demonstrated that gender gaps in the workforce and the unequal sharing of household responsibilities can severely impede economic growth and development [@elson2009; @berik2009; @duflo2012].
Yet, public policies and collective actions have been less than adequate, especially in poorer countries due to constrained fiscal capacity, widespread absence of formal wage labor, and weak welfare states.
Moreover, in patriarchal contexts, cultural barriers also restrict redistribution of household production among their members, or redistribution between the public and private spheres.
While in some developed countries such as Norway and Sweden, public policies have been able to promote gender-equitable sharing of household production, such as paid paternity and maternity leaves, they have attained limited attention and success in other countries.

The U.S. is not an exception.
Issues related to lack of public provisioning of care infrastructure and services, widespread existence of childcare deserts, and lack of paid parental leave laws, among others, have drawn attention.
In 2021, the value of unpaid household work in the U.S. amounted to $600 billion, constituting approximately 2.6% of the GDP [@rein2023].
Moreover, like most other countries, we observe gender disparity in sharing of household work, with women being in charge of a disproportionately larger share of the burden.
According to the 2018 American Time Use Survey, among adults aged 15 and older, women on average spent 5.7 hours per day on unpaid household and care work, compared with 3.6 hours for men.
In other words, women spent 37 percent more time on unpaid household and care work than men [@hess2020].

```{=html}
<!--
lets leave this for now
The disparity is more significant between married men and married women xxxx(TBD) and also in households where children are present. -->
```

Unfortunately, the U.S. also falls behind in other dimensions of this problem.
Compared to other OECD countries, the U.S. lacks effective childcare policies, spending only 0.4% of GDP on early childhood education and care (ECEC), compared to the OECD average of 0.8% [@oecd2020].
The U.S. also lacks federal laws granting paid parental leave, setting it apart from other OECD nations.
Around 51% of the U.S. population resides in childcare deserts, defined as census tracts with more than 50 children under the age of 5 and either no childcare providers or significantly limited options, resulting in a severe shortage of licensed child care slots [@malik2018].

## What does this mean for time poverty?

The lack of public provisioning of care infrastructure and services, and the disproportionate burden of household production on women, has implications for time poverty, both at the individual and the household/family level.

But what should we understand as time poverty?

Over the last decades, the Levy Economic Institute has been at the forefront of recognizing the importance of time for understanding income and poverty dynamics [@zacharias2011].
As part of this work, they developed a new measure of poverty that incorporates the dimension of time into traditional poverty measures: The Levy Institute Measure of Time and Income Poverty (LIMTIP for short).
This measure uses synthetic data in order to incorporate the value of time, or more specifically the amount of resources required to outsource the responsibilities that cannot be covered by the household members, into traditional measures of poverty thresholds.
By incorporating this dimension, the LIMTIP not only provides a more comprehensive understanding of poverty but also allows for the identification of the hidden poor, i.e., individuals whose families do not have enough monetary resources to accommodate for the time deficits they face [@zacharias2021; @masterson2012; @Antonopoulos2017; @zacharias2012; @zacharias2014; @zacharias2018].

In principle, individual time poverty refers to the lack of time available for individuals to engage in activities that are essential for taking care of the household, its members, self-care, and paid work.
This in itself is a difficult concept to grasp, because every individual has different responsibilities and needs, and thus, different time constraints.
To formalize this definition, LIMTIP assumes that all individuals have the same time constraints (168 hours per week) that they need to allocate among household production, personal maintenance, and paid work.
Some of these components are identified based on people's decisions (i.e., time spent on paid work), but others are assumed to have some minimum time requirements, such as the case for household production and personal maintenance.
If the responsibilities of an individual exceed the 168 hours per week,

To identify time poverty at the household level, LIMTIP imposes the assumption that individuals are unable or unwilling to help those with time deficits.
Thus, even if a single individual struggles to meet their responsibilities, the whole family is considered to be living under time poverty.
In this framework, as pointed out in @policybrief_USLIMTIP, it is not uncommon to see households with a mixture of time availability (i.e., deficits and surpluses) among its members.
In fact, just over 20% of the working-age population are not time-poor but live in a household where at least one person lives under time poverty.
Because the LIMTIP assumes household production is the only component that can be shared among household members, this mixture of time availability among household members suggests that not everyone is pulling their weight in terms of household production.

In spite of the growing recognition of the importance of time constraints and the responsibility of household production, the issue of time poverty has received limited attention in the U.S., partially due to data availability constraints.

<!-- 20% for what year?-->

What does this mean for Time Poverty in the U.S.?

While most of the earlier work on LIMTIP has focused on the analysis of time poverty in developing countries [@masterson2012; @zacharias2018; @masterspm2022], recent work has extended the measure to the U.S. [@zacharias2024a; @policybrief_USLIMTIP].[^1]
Similar to earlier work, one of the findings of @policybrief_USLIMTIP is that a large share of the population experiences some level of time poverty, which translates into a significant share of households who are ***hidden poor***, thus not captured by the official income poverty measure.
In this policy brief, we suggest that a significant share of time-poor individuals and households could potentially exit time poverty if household production responsibilities were to be redistributed among its members (similar to @zacharias2021).

[^1]: This is in addition to the work done for the Levy Institute Measure of Economic Well-Being (LIMEW).

Following @policybrief_USLIMTIP, this policy brief explores the potential impacts of redistribution further.
Using the new estimates for LIMTIP for the U.S., we provide insights into how redistributing household production can reduce the incidence of poverty not only for individuals but also of the households they live in.
Specifically, given the marked responsibilities gap between men and women, we focus on analyzing the impact of redistribution among married couples.
To do this, we consider three redistribution scenarios based on equality, equity, and opportunity cost principles and assess the impact of redistribution on time poverty of working-age (18-64 years) household members who are part of a heterosexual couple.
Further, we present the impacts for different household types, household structures (presence of young children and other members), poverty groups and employment status.

```{=html}
<!--

Im thinking taking this out for the Policy brief, as this was lightly explained earlier

In the next section, we start by briefly describing the LIMTIP measure and our estimates for the US. We then move on to identifying the different types of households experiencing time poverty, the redistribution scenarios, followed by results and policy implications.

# LIMTIP: A New Measure of Time Poverty for the United States


-->
```

[The rest of the document remains the same as the original, with the corrections applied throughout]