---
title: "Redistribution and Time Poverty: Balancing Responsibilities in Couple Households"
format:
  simart-pdf:  
    keep-tex: true  
    fontsize: 11pt
    number-depth: 3
  docx: default
author:
    - name: "Fernando Rios-Avila"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504
    - name: "Aashima Sinha"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504
    
date: today
keywords: "Time Poverty, Income Poverty, Redistribution, household production, care work, gender equality, LIMTIP"
abstract: |
    This policy brief examines how redistributing household production responsibilities could reduce time poverty among married U.S. couples. Using the Levy Institute Measure of Time and Income Poverty (LIMTIP), we analyze three scenarios based on equality, equity, and opportunity cost principles. Our findings show that redistribution could effectively reduce time poverty in households where time surplus exceeds deficits, with the equity-based approach proving most successful. However, redistribution has limited impact when all household members are already time-poor. The effectiveness varies across household types and structures, suggesting targeted approaches may work better than universal solutions.

bibliography:
  - publications.bib
  - biblio.bib
  - references.bib
---

<!--Isnt this sentence in the abstract obvious? However, redistribution has limited impact when all household members are already time-poor. -->

# Introduction

Redistribution of household production, which includes unpaid caregiving and domestic chores, has been identified as an important tool to achieve gender equality.
The United Nations Sustainable Development Goal 5, Target 5.4, has incorporated the recognition, reduction, and redistribution of unpaid work strategy, popularly known as the 3R strategy.
This is a testament to decades of activism and advocacy emphasizing that gender inequality on this front cannot be simply justified as a "private family matter", but rather be considered a matter of public policy.
Redistribution can take place from households to the public and/or private spheres, as well as among household members.Evidence shows that it is disproportionately undertaken by girls and women globally [@addati2018].

While redistribution of household production responsibilities from women to men is important intrinsically for human rights and fairness concerns; it is also instrumental in achieving gender equality in labor market outcomes [@hundt1996; @elson2017; @valeria2016].
Studies have demonstrated that gender gaps in the workforce and the unequal sharing of household responsibilities can severely impede economic growth and development [@elson2009; @berik2009; @duflo2012].
Yet, public policies and collective actions have been less than adequate, especially in poorer countries due to constrained fiscal capacity, widespread absence of formal wage labor, and weak welfare states.
Moreover, in patriarchal contexts, cultural barriers also restrict redistribution of household production among their members, or redistribution to the public and private spheres.
While in some developed countries such as Norway and Sweden, public policies have been able to promote gender-equitable sharing of household production, such as paid paternity and maternity leaves, they have attained limited attention and success in other countries.

The U.S. is not an exception.
Issues related to lack of public provisioning of care infrastructure and services, widespread existence of childcare deserts, and lack of paid parental leave laws, among others, have drawn attention.
In 2021, the value of unpaid household work in the U.S. amounted to \$600 billion, constituting approximately 2.6% of the GDP [@rein2023].
Moreover, like most other countries, we observe gender disparity in sharing of household work, with women being in charge of a disproportionately larger share of the burden.
According to the 2018 American Time Use Survey, among adults aged 15 and older, women on average spent 5.7 hours per day on unpaid household and care work, compared with 3.6 hours for men.
In other words, women spent 37 percent more time on unpaid household and care work than men [@hess2020].

Unfortunately, the U.S. also falls behind in other dimensions of this problem.
Compared to other OECD countries, the U.S. lacks effective childcare policies, spending only 0.4% of GDP on early childhood education and care (ECEC), compared to the OECD average of 0.8% [@oecd2020].
The U.S. also lacks federal laws granting paid parental leave, setting it apart from other OECD nations.
Around 51% of the U.S. population resides in childcare deserts, defined as census tracts with more than 50 children under the age of 5 and either no childcare providers or significantly limited options, resulting in a severe shortage of licensed child care slots [@malik2018].

## What does this mean for time poverty?

The lack of public provisioning of care infrastructure and services, and the disproportionate burden of household production on women, has implications for time poverty, both at the individual and the household/family level.

**What do we mean by time poverty?**


Poverty is a multidimensional concept that goes beyond the simple notion of lack of income.
In addition to income, poverty can be understood as a lack of access to resources, including time.
Over the last decades, the Levy Economic Institute has been at the forefront of recognizing the importance of time for understanding income and poverty dynamics [@zacharias2011].
As part of this work, they developed a new measure of poverty that incorporates the dimension of time into traditional poverty measures: The Levy Institute Measure of Time and Income Poverty (LIMTIP for short).The LIMTIP is a metric that, in addition to income poverty, incorporates aspects of time poverty that better capture the control households have over their resources.
This measure uses synthetic data in order to incorporate the value of time, or more specifically the amount of resources required to outsource the responsibilities that cannot be covered by the household members, into traditional measures of poverty thresholds. The 
By incorporating this dimension, the LIMTIP not only provides a more comprehensive understanding of poverty but also allows for the identification of the hidden poor, i.e., individuals whose families do not have enough monetary resources to accommodate for the time deficits they face [@zacharias2021; @masterson2012; @Antonopoulos2017; @zacharias2012; @zacharias2014; @zacharias2018]. <!--FRA please check-->This group of hidden poor are those who are not considered poor by official income poverty measures, but are classified poor when we adjust for time poverty. Therefore, LIMTIP provides a peep into this group of people and can allow for more extensive poverty alleviation and welfare programs. 

In principle, individual time poverty refers to the lack of time available for individuals to engage in activities that are essential for taking care of the household, its members, self-care, and paid work.
This in itself is a difficult concept to grasp, because every individual has different responsibilities and needs, and thus, different time constraints.
To formalize this definition, LIMTIP assumes that all individuals have the same daily time constraints, 24 hours per day (168 hours per week) that they need to allocate among household production, personal maintenance, and paid work.

 For the identification of time poverty, using weekly hours as the unit of analysis (168 hrs per week), we identify the amount of time individuals would have left ($X_{ij}$) after engaging in required activities for taking care of their share of responsibilities ($\alpha_{ij}$) in household production ($R_j$), personal maintenance ($M$), and paid work (commuting $T_{ij}$ and time spent at work $L_{ij}$). This is expressed in the following equation (see @eq-bal):

$$X_{ij} = 168 - M - \alpha_{ij}R_j-D_{ij}(L_{ij}+T_{ij})
$$ {#eq-bal}

Some of these components are identified based on people's decisions (i.e., time spent on paid work), but others are assumed to have some minimum time requirements, such as the case for household production and personal maintenance.
If the responsibilities of an individual exceed the 168 hours per week, <!--incomplete sentence-->

An individual is classified as time poor if they have a negative time balance based on equation @eq-bal. 

<!-- can drop this and keep the next para below :To identify time poverty at the household level, LIMTIP imposes the assumption that individuals are unable or unwilling to help those with time deficits.
Thus, even if a single individual struggles to meet their responsibilities, the whole family is considered to be living under time poverty. -->

At the household level, however, we assume that individuals with time surpluses are unable or unwilling to share and redistribute some of the responsibilities of those with time deficits. In this framework, a household is considered to be time-poor as long as there is atleast one person with a time deficit living in the household.[^2] This is expressed in the following equation (see @eq-hbal):

[^2]: To identify time poverty status, we only consider the time deficits of household members age 18 or older.

$$X_{j} = \sum_{i=1}^{I_j} \min(X_{ij},0)
$$ {#eq-hbal}

Once household time deficits $X_{j}$ are identified, we adjust the official income poverty thresholds to account for the monetized value of the time deficits. The adjusted poverty line is then calculated as:

$$Z_{j}^{adj} = Z_{j} + 52*P* |X_{j}|
$$ {#eq-limtip}

where $P$ is the price we use to give a monetary value to the time deficits the household ${j}$ faces, $Z_{j}$ is the official poverty line (SPM Poverty line), and $Z_{j}^{adj}$ is the adjusted poverty line. Intuitively, households that are not time-poor will not change status compared to the official poverty estimates. However, households that are time-poor could have their poverty status change if, after considering the adjusted poverty line, they fall below it. This group of households is considered to be the hidden poor.
<!-- thought may be we should add all three equations, but open to droping if you prefer that-->

In this framework, as pointed out in @policybrief_USLIMTIP, it is not uncommon to see households with a mixture of time availability (i.e., deficits and surpluses) among its members.  
<!--AS edited--> The mixture of time availability among household members suggests that not everyone may be pulling their weight in terms of household production. We therefore, tap the scope of redistributing  household production among household members with the objective of more equitable sharing of housheold work as well as reducing time poverty incodence of the household.  

In spite of the growing recognition of the importance of time constraints and the responsibility of household production, the issue of time poverty has received limited attention in the U.S., partially due to data availability constraints.


**What does this mean for Time Poverty in the U.S.?** 
While most of the earlier work on LIMTIP has focused on the analysis of time poverty in developing countries [@masterson2012; @zacharias2018; @masterspm2022], recent work has extended the measure to the U.S. [@zacharias2024a; @policybrief_USLIMTIP].[^1]
Similar to earlier work, one of the findings of @policybrief_USLIMTIP is that a large share of the population experiences some level of time poverty, which translates into a significant share of households who are ***hidden poor***, thus not captured by the official income poverty measure.
In this policy brief, we suggest that a significant share of time-poor individuals and households could potentially exit time poverty if household production responsibilities were to be redistributed among its members (similar to @zacharias2021).

[^1]: This is in addition to the work done for the Levy Institute Measure of Economic Well-Being (LIMEW).

Following @policybrief_USLIMTIP, this policy brief explores the potential impacts of redistribution further.
Using the new estimates for LIMTIP for the U.S., we provide insights into how redistributing household production can reduce the incidence of poverty not only for individuals but also of the households they live in.
Specifically, given the marked responsibilities gap between men and women, we focus on analyzing the impact of redistribution among married couples.
To do this, we consider three redistribution scenarios based on equality, equity, and opportunity cost principles and assess the impact of redistribution on time poverty of working-age (18-64 years) household members who are part of a heterosexual couple.
Further, we present the impacts for different household types, household structures (presence of young children and other members), poverty groups and employment status.


# Where we are: Time Poverty in the United States

Between 2015 and 2019 in the U.S., under LIMTIP definition, an average of 35.0% of all households had at least one member who was time poor. If we restrict this to households with a married couple, this share increases to 36.1%, providing a glimpse of high prevalance of time poverty among married couples. This group consitutes the focus of our analysis.

Within these time poor housheolds, 52% of the married couples may be classified as time poor, with only 7.8% of other members in the household experiencing time poverty.
From this share of time poor married couples, 44% of married men are experiencing time poverty compared to 61% among married women.
<!-- The shares of required hours of household production reflects gender disparity in sharing of hh work and  it has stayed more or less stagnant during this period (add a figure 2015-19 srhp by sex). In Figures 1 and 2, we present the shares of housheold production and time defeicits experienced by married men and women.
-->

**Who are the couples in this time poor households?**
<!-- consider breaking Table 1?-->

@tbl-stat provides an overview of the characteristics of the households where these couples live.

The first type of classification we consider is one that classifies households in regards to their potential to exit time poverty via redistribution. Households can vary in  terms of the presence of time poor and time non-poor members and in terms of the total time deficit and surplus.  Members with time surpluses could take on more household responsibilities, reducing the burden of those with time deficits, and potentially lifting the household out of poverty.  Even if the household remains time-poor, redistribution could still make the time deficits more equal among the household members, particulalry balancing the share between men and women.
We consider three types of households:

-   Households where everyone is time poor, thus redistribuion cannot eliminate time poverty for the household.
-   Households where there is at least one non-time poor individual, but its insufficient to eliminate time poverty for the household, and
-   Households where the total time surplus is greater than the total time deficit, thus redistribution can eliminate time poverty for all members in the household.

Overall, 5.2% of couples live in a household where all members are time poor, but 76% could potentially leave time poverty if household production responsibilities were to be redistributed.
Over half of the couples have a young child living with them (56%) and 25% have other members in the household.
In terms of employment status, the vast majority of working-age individuals are employed, with 97% of husbands and 91% of wives are working.
This is not surprising, as discussed in @policybrief_USLIMTIP, for most individuals, time poverty is driven by the need to work.

**what about other characteristics?**

As shown in @tbl-stat, household struture is a critical factor for understanding if redistribution has the potential to reducing time poverty.
Household with young children have the lowest chance to exit time poverty (65.5%), compared to other groups.
In contrast, the presence of other age-able members in household drastically increases those chances (97.3%).
This is not surprising.
The presence of young children increases the time demands on the child care activities, as well as overall household activities due to larger size.
On the other hand, the presence of a fall back person for the couple greatly increases the potential of redistribution, because of of this "other-members" do not typically experience time constrains.

A third pattern observed relates to wife employment status.
Families where wives are not currently working show higher potential for time redistribution reducing time poverty.
However, this is also observed alongside two other characteristics of these families: they tend to have young children, while also showing a larger proportion of additional household members present.

```{=html}
<!--- Further, in Table xx we present the four-way classification of limtip estimates for individuals. We find that xx % women experience double poverty: income poor and time poor. Given these time poverty outcomes, we investigate the impact of redistribution of household production work among all eligible members in time poor housheolds (18-64 and abled). Our focus is on married couples and we examine if redistribution between them and to other hh members can reduce time poverty. 
Moroever, 5.6% of households are hidden poor, i.e those who are not classified poor based on official poverty estimates but are poor based on LIMTIP estimation. We finally explore the potential of redistribution in lifting households out of poverty and reducing the share of hidden poor. 
-->
```

::: {#tbl-stat tab-pos="!H"}
\resizebox{\textwidth}{!}{%
{{< include table/tb1.tex >}}
}

Summary Statistics Population
:::



# Where we are going: Redistribution Scenarios

The idea of redistribution of household production responsibilities follows the principle that everyone in a household should be able to carry out their **fair** share of household work.
But what constitutes a fair share?
While one could construct many rules and strategies to redistribute household responsibilities within a household, we consider three principles that could guide the redistribution of household production responsibilities among eligible household members.

For the implementation of these scenarios, we consider that all other elements in LIMTIP @eq-bal remain constant with the exception of $\alpha_{ij}$, which is the share of household production time that each individual $i$ in Household $j$ takes on.
The goal is to simulate different $\alpha_{ij}$ based on each redistribution scenario, but maintaining the total share of work done by the eligible household members (all members 18-64).
This approach imposes the implicit assumption that all household members are equally efficient at taking care of the household responsibilities. We outline the methods used for implementing the scenarios below.

## Scenario 1: Equal Shares

The first scenario considers the impact of redistributing household production such that all responsibilities are equally distributed across all eligible household members.

$$\alpha_{ij}^E= \frac{1}{I_j}*(1-\alpha_{j}^{nw})
$$ {#eq-r1}

where $\alpha_{ij}^E$ represents the redistributed share of individual $i$; $I^j$ is the number of working-age persons in household $j$ and $\alpha_{j}^{nw}$ represents the total share of all non-working age household members.
While this principle aligns with the idea of equality, it overlooks time equity by redistributing tasks without taking into consideration the time available to individuals.

## Scenario 2: Time Available

The time available scenario is based on the principles of equity.
In contrast with Scenario 1, this one suggests that household responsibilities should be redistributed relative to the available time individuals may have after setting aside the time for personal maintenance requirements, and income generation ($Z_{ij}=168-M-D_{ij}(L_{ij}+T_{ij})$).

To implement this, we first calculate the time available ($Z_{ij}$) for each individual and recalculate the shares $\alpha_{ij}^A$ using the ratio of time available to the total time available among working-age members.
For individuals that do not have any time available ($Z_{ij}<0$), we set it at zero.
This ensures that people who already suffer from time poverty are not assigned further tasks within the household.
The new share is defined as:

$$
\begin{aligned}
Z_{ij} &=\max{\Big(168-M-D_{ij}(L_{ij}+T_{ij}-E_{ij}(S_{ij}),0\Big)} \\
\alpha_{ij}^A &= \frac{Z_{ij}}{\sum Z_{ij}} (1-\alpha_{j}^{nw})
\end{aligned}
$$ {#eq-r2}

Because there are individuals (young adults) who may still be in school, we adapt the definition of $Z_{ij}$ by discounting from their available time the average number of hours people spend in education activities per week ($S_{ij}$).
This correction does not affect the time balance used for the identification of the time poor, only the estimation of time available and the adjusted shares $\alpha_{ij}^A$.

## Scenario 3: Opportunity Cost

The third possibility is based on the idea of opportunity costs along marginalist lines.
The sharing rule depends on the earning potentials of individuals, such that individuals with higher potential wages are assigned a lower share of household production time.
In principle, this would encourage the most productive members of the household to spend more time in paid work, while those with lower earning potentials would take on more household production responsibilities.
However, because we do not implement any changes in the time spend on paid work, we could also interpret this scenario as a bargaining case where members with the highest potential earnings are able to negotiate a lower share of household production time.

For example, if there are only three working-age adults in a household, and where the second member earns twice as much as the first, and the third earns three times as much as the first, the shares of household production would be 1/2, 1/3, and 1/6 respectively.
To implement this scenario, we first calculate the inverse of the wage of each individual $rw_{ij}$, and then calculate the share of household production time as follows:

$$\begin{aligned}
rw_{ij} &= \frac{1}{w_{ij}}, \ 
\alpha_{ij}^O &= \frac{rw_{ij}}{\sum rw_{ij}} (1-\alpha_{j}^{nw})
\end{aligned}
$$ {#eq-r3}

where $w_{ij}$ is the wage of individual $i$.

Because wage data is not observed for all household members, we use potential/predicted wages for all working-age household members, based on a two step procedure.
First, we predict the occupation and industry likelihood for non-working individuals, and second, we model and predict wages for all household members using a method (heckman selection - @heckman1979) that accounts why some people choose not to work in the first place (self-selection).
These predicted wages serve as our measure of how valuable each person's time is.

# Impact of Redistribution

Because there are many household members that could potentially take on more household production responsibilities, the potential for redistribution is high.
However, the effectiveness depends considerably on characteristics of the household, such as the presence of children, the presence of other members, and the employment status of the wife.
Furthermore, because the redistribution scenarios are based on a zero-sum game, there are individuals that may not benefit from redistribution.

::: {#tbl-tb2 tab-pos="H"}
{{< include table/tb2.tex >}}

Time Poverty and Transition Rates
:::
<!-- add notes to tables-->

In terms of incidence of time poverty, see @tbl-tb2, women benefit more from redistribution than men, except under Scenario 3.
This shows that even the simplistic redistribution rules we defined, the gender wage gap has important implications in terms of women's time poverty.
In terms of numbers, the simulations suggest that Scenario 2 is the most effective in reducing time poverty for both men and women, bringing the share of time poor individuals to 29.6% (men) and 26.4%(women).

These improvements do not come without casualties.
Among non-time poor men (baseline), we estimate that up 23% of them could enter time poverty under redistribution scenario 1, with a lower end of 13.7% under scenario 3.
In contrast, while there is generally a smaller rate of women falling into time poverty , the transition into poverty rate under scenario 3 (16.3%) is higher than that observed for men.
This reinforces the idea that gaps in opportunity costs/bargaining power can have important implications for the redistribution of time and could affect time poverty.

The type of the household also plays an important role in the effectiveness of redistribution.
Even in cases where everyone in the household is time poor, redistribution can still reduce the time poverty status individuals.
While this improvements are small for men, there are significant reductions in time poverty for women under the equal shares scenarios (Scenario 1).
As we will see later, however, this should not be interpreted as a general improvement, as someone else in the household will have to take on the extra responsibilities, and thus increasing their own and the household time decifit. 
The results that appear to be the most paradoxical relate to households where there are non-time poor individuals, but the total time surplus is not enough to eliminate time poverty.
Based on individual time poverty alone, it may seem that all redistribution scenarios have a negative impact on both husbands and wives.
This, however, is also in contrast with the fact that time deficits would be decreasing, despite the increase in time poverty incidence. <!--above para not clear>

Lastly, for household that can exit time poverty, most of their members (husband and wife) will exit time poverty.
And just as described before, both men and women benefit greatly under Scenario 2, with scenario 1 being the least favorable for men, and scenario 3 the least favorable for women.

**The role of household Structure**

The results we just presented provides us with an overall picture of the potential of redistribution to reduce time poverty.
However, the effectiveness of redistribution also depends on the structure of the household.
There are two factors, as observed in @tbl-tb3, that are important to understand how effective redistribution can be: the presence of young children and the presence of other members in the household.

On the one hand, presence of young children (14 years or younger) will have a large impact on the requirements of household production, mostly in the form of child care activities, without the possibility of the children taking on any of the responsibilities.[^3]
On the other hand, if there are other members in the household, the potential for redistribution is higher, as these members could potentially take on some of the responsibilities of the couple.

[^3]: By construction, the ATUS does not collect information on time use of individuals younger than 15

Interestingly, at baseline, the presence of children, and presence of other household members, are weakly associated with time poverty differences across husband and wife.
The small differences we observe are as expected, with somewhat higher levels of time poverty across households with children, and households without other members.

::: {#tbl-tb3 tab-pos="H"}
{{< include table/tb3.tex >}}

Time Poverty by Household Structure
:::

When considering the impact of the redistribution scenarios, we find a clear pattern that the presence of children and absence of other members have a very similar impact reducing the effectiveness of redistribution scenarios.
In both cases, the reduction in time poverty we estimate for women is still larger than that for men.
This highlights how much more work women do in taking care of the household, specially providing primary child are, as well as absorbing most of the responsibilities of the household production, when there are no other members to share the responsabilities.
This also explains why, when redistribution is applied, the reduction in time poverty is more limited for husbands.

**Income and Emplyoment**

One last aspect to consider is to analyze if there is any heterogeneity in the estimated impact of redistribution based on the household overall income or the employment status of the wife.
We do not consider the employment status of the husband, because 97.2% of husbands are employed, and thus, there is little variation to analyze.
We should also remember that we concentrate on households that are time poor, and thus are less likely to be income poor, because one or both of the partners are employed.

::: {#tbl-tb4 tab-pos="H"}
{{< include table/tb4.tex >}}

Time Poverty by Income
:::

We first consider the impact of redistribution based on the household income, or more specifically, the income-to-poverty-line ratio.
Interestingly, it may seem that time poverty, at baseline, does not discriminate across income groups, showing similar levels across the income distribution.
Although we do observe a slightly lower share of time poor women (55.9%) in the lowest income group, compared to average of 61.0%.

For men, there is very little variation in the impact of redistribution across income groups for scenarios 1 and 3.
It may seem that men will either increase their share of household production (Scenario 1) or will take advantage of the opportunity cost of time (Scenario 3), regardless of the income.
For Scenario 2, however, we observe that redistribution is more effective in reducing time poverty for those in the lowest income group.

What is more interesting is that the same pattern of decreasing effectiveness of redistribution policies is also observed among women, for all scenarios.
A possible explanation is that the share of employed men does not vary much across income groups.
However, the share of non-employed women goes from 30% in the lowest income group, to 5% in the highest income group.
This means that for people in the highest income group, there is less room for redistribution because both husband and wife are employed.
However, because women still take on most of the household production, the impact of redistribution is still higher for them compared to men

**What about the Hidden Poor?**

One of the main contributions of the LIMTIP is the identification of the hidden poor, i.e., individuals who are not classified as poor based on official poverty estimates but are classified as such when one accounts for the time deficits they face.
For our sample, we estimate that 4.7% of the population who is not classified as officially poor, fall under this definition with when we adjust time deficits.
However, if any of the redistribution scenarios were to be implemented, the share of hidden poor could be reduced to 1.8-0.7%.

When considering household characteristics, redistribution scenarios could actually increase hidden poverty in households where everyone is time poor, but can be greatly reduced whenever there is room for redistribution.
For example, if the household has the potential to exit time poverty, redistribution based on the time available principle could almost eliminate the share of hidden poor (0.1%).

Lastly, when the wife is working, redistribution based on equal shares or opportunity cost are almost ineffective in reducing the share of hidden poor, probably because the wife is already doing the bulk of household production, and redistribution would only increase the time poverty of other members.
However, if she is working, as is the case for 91% of the sample, redistribution will help reduce the double burden of time women face.

::: {#tbl-tb5 tab-pos="H"}
{{< include table/tb5.tex >}}

Hidden Poor by Characteristics
:::

# Policy Implications: Opportunities and Challenges


The findings in this policy brief suggest that intra-household redistribution of household production is a potentially effective tool to reduce time deficits and alleviate time poverty for individuals and households. Our findings show that such redistributions can have significant well-being effects, promoting more equitable sharing of household responsibilities between husbands and wives and, in some cases, lifting entire households out of poverty.

However, the effectiveness of redistribution policies is contingent on the type and structure of households. For instance, in households where all members are time-poor, redistribution may not be effective and could potentially (slightly) increase LIMTIP poverty. In contrast, households with sufficient time surpluses to absorb time deficits can effectively eliminate time poverty under any of the proposed redistribution policies. Moreover, presence of chilren in housheodls would call and xxx..
Among the three redistribution scenarios considered, the equity-based approach emerged as the most effective in reducing poverty rates and enabling individuals to exit poverty.

While redistribution policy may be difficult to implement, public polices can help target inequalities in terms of "time availability" and "opportunity cost" experienced by men and women, which are a result of  gender discriminatory vicious cycle that hinders equal educational opportunities for women leading to unequal occupation opportunities as well as earning cabailities (@sinha2024). 
Policy initiatives that can contribute towards a more gender-equitable sharing of hosuehold production can be segregated into three broad categories:

- Labor market or employment policies to reduce gender disparity: This would involve targetting equal pay at work for men and women and ensuring elimination of gender discrimination at workplace. Moreover, long-working hours that directly impact time constraints may also need to be regulated. 
- Public investment in care infrastructure and services: This can be helpful as it can contribute toward reducing the required hours of household production that determine people's time deficits and time poverty. Efforts can involve provisioning of quality childcare services at subsidized rates and can even be extended to a universal and centralized provisioning of care services. In addition, parental leave laws offering not only maternity leave benefits but those combined with paternity leaves may serve to have more gender-equitable effects on household division of labor. 
-  Targeting social norms: Gender disparity in labor market are guided by gender norms defining gender roles. Targeting norms could involve educational interventions during early schooling years, gender equitable knowledge-sharing as part of couple counseling on how gender norms can be detrimental for the overall well-being and deevlopment of the society and the economy. 

# Conclusion/recommendations


This policy brief has examined the potential of redistributing household production responsibilities to alleviate time poverty in the United States. Using the Levy Institute Measure of Time and Income Poverty (LIMTIP), we have shown that time poverty is a significant issue affecting married couples, about 36% of households with couples experienced time poverty. Our analysis of three redistribution scenarios - based on equality, equity, and opportunity cost principles - reveals that such redistributions can significantly reduce time poverty, particularly in households where time surpluses exceed time deficits.

These findings underscore the importance of integrating time poverty in poverty alleviation efforts.
They also highlight the potential of intra-household redistribution as a policy tool to promote gender equality and improve overall household well-being. However, the varying effects across household types, household structures, poverty groups and employment status of wives, along with variations across redistribution scenarios suggest that a one-size-fits-all approach may not be optimal and a targeted tailored approach is needed.

In conclusion, while redistribution of household production is promising in alleviating time poverty, and the hidden poor, it should be considered as part of strategies that also addresses societal and structural factors affecting to time and income poverty.

# References {.unnumbered}