---
title: "Impact of Redistribution of Household Production on Time Poverty and Gender Equality: Evidence from the United States "
format:
  simart-pdf:  
    keep-tex: true  
    fontsize: 11pt
    number-depth: 3
  docx: default
author:
    - name: "Fernando Rios-Avila"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504
    - name: "Aashima Sinha"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504
    - name: "Ajit Zacharias"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504   
    - name: "Thomas Masterson"
      affiliations:
        - name: "Levy Economics Institute"
          address: Annandale-on-Hudson, NY 12504       
date: today
keywords: "Time Poverty, Income Poverty, Redistribution, household production, care work, gender equality, LIMTIP"
abstract: |
    This paper examines the potential of redistributing household production responsibilities to alleviate time poverty and promote gender-equitable sharing of unpaid work in the United States. Using the Levy Institute Measure of Time and Income Poverty (LIMTIP), we explore three redistribution scenarios based on equality, equity, and opportunity cost principles for different classification of housheolds which in turn are based on the mix of time surplus and time deficits. Findings indicate that redistribution can significantly reduce time poverty, particularly in households where time surpluses exceed time deficits and where there are xx children, employment?, vv. Further, we find that equity-based approach emerges as most effective in reducing poverty rates overall and xx being most effective in reducing disparity between men and women. The paper draws policy implications along the lines of the 3R strategy such that the third "R" of redistribution (focusing on intra-hh redistribution) can be tapped to promote more equitable sharing of responsibilities between men and women and potentially lift entire households out of poverty. Since, effects vary across household types and scenarios, a one-size-fits-all approach may not be optimal and a tailored approach is needed. 
 
bibliography:
  - publications.bib
  - biblio.bib
  - references.bib
---

# Introduction

- Motivation: Global secnario: why these are imp issues
- Problem at hand
- How we propose to mitigate it/Explain what we do 
- Contribution


Unpaid care work is recognized as a critical human rights issue, particularly for women caregivers, especially those experiencing poverty . The UN Special Rapporteur on Extreme Poverty and Human Rights highlights that disproportionate care responsibilities hinder gender equality and women's full realization of their rights, often further trapping them in poverty. Besides a humar rights concern, unpaid work burden could have multi-dimesional consequences for care providers.
Feminist scholars, political activists and policymakers  have articulated that the redistribution of household production responsibilities from females to males is important for its own sake, as well as for achieving gender equality in labor market outcomes (Bruyn-Hundt 1996; Elson 2017; Esquivel 2016). 
Globally, women and girls do the vast majority of the unpaid household work, including chores and caring for children, the elderly, and the sick.  This unpaid work is essential for households and economies to function, but it restricts the care providers' capabilities by restricting their time availability, particpation in the labor market and well-being outcomes (@sinha2024). Addressing the disparities in unpaid care work can lead to improved health and well-being for women and families and foster more equitable societies​(@oxfam2020). Informal caregivng exerts additional pressure on indivuidsulas time availability especially among employed people. Time poverty xxxx
The 3R statetgy : recognize, reduce and redistribute unpaid work have gained attention in research and polciy spaces alike (@elson2017; @UN2015). Recognition focuses on  measuring time use in households and integrating them into national statistical systems; Reduction aims to expanding access to key infrastructure, and investing in time and labour-saving technologies; and Redistribution emphasize on implementing policies favourable to burden-sharing between women and men, such as maternity and paternity leave, and quality public care services, as well as eliminating gender wage gaps. 

In this paper we focus on the redistribution aspect of the 3R framework. We explore if redistributing housheold production among members can reduce time poverty, and promote gender equitable sharing of housheold work. We explore the possibility of reducing individual's time poverty ouctomes as well as if hosuheolds can be lifted out of time-adjusted income poverty.  While intra hosuheold time allocation has been studied widely in theory (), limted empirical work exist on redistributing hh production and its interaction with poverty outcomes. Extending the research on sub-saharan Africa in xxx, to the US we emprically investigate the impact of redistribution on a range of outcomes such as time deficits, time poverty, income poverty and gender equality. Moreover, we investigate the imapct across different housheold structures including presence of children, employment status of spouses, xx, xx;  factors identified in the literature as influencing individuals' time constraints and the unequal division of labor. We use the ATUS and ASEC data to estiamte the impact of redistribution simulations for the US economy for the period 2015-19.




# Literature 
- Time poverty
- HH production gender disparity
- 3R strategy redistribution goal
- Intra HH redistribution theories

The division of unpaid work within households and the underlying power dynamics have been central to feminist economics, which challenges the assumptions of mainstream economic models and highlights the gendered nature of household labor. Feminist scholars argue that traditional economic theories, particularly those rooted in neoclassical frameworks like the unitary household model, fail to adequately account for the unequal distribution of unpaid labor, which disproportionately burdens women. 

Becker’s theory of time allocation (1965)is often used to understand the gender division of labor in the household. It explains why women may specialize in home production while men in the labor market, based on differences in wages and the opportunity cost of time. Becker’s model predicts that if women have a comparative advantage in doing domestic activity and men in market activity, then women would specialize in the former and men in the latter (Becker, 1981; 1985). The household if taken as a unit of analysis with common preferences of all members is gender blind to individual preferences, norms and power differential between men and women that lead to this comparative advantage in the first place. 

Standard neo-classical economics understands well-being as utility maximization by rational individuals. Becker (1965) made a breakthrough in mainstream economics by incorporating division of labor between men and women in unpaid and paid work, this was restricted to maximizing household welfare based on role specialization. This utilitarian model conceptualizes gender difference in how individuals allocate their time across paid work, unpaid care work, leisure, and domestic chores based on relative opportunity costs and marginal utility gains. The model does not incorporate gender differences that arise due to susytemic gender discrimination and intra-household power differential rooted in patriarchal norms; rather, they are often based on assumption of individual rationality, homogenous home goods/tasks, and short-term horizon of individuals, that may not be applicable to the real world (Blau and Winkler 2018). 

Distinct from the comparative advantage approach, studies have long emphasized the role of social norms in shaping time allocation (Castle, 1993). Fafchamps and Quisumbing (2003), for example, find that in rural Pakistan the gender-based division of labor cannot be completely explained by systematic differences in comparative advantage and that social and kinship roles play an important role in determining who undertakes which task. Gender norms define gender roles, bargaining power of men and women and women’s agency within households (Folbre, 1994; Gammage, Kabeer, Rodgers 2016). 
Benería (2003) demonstrates how patriarchal power structures influence both the distribution and valuation of household labor.

Moroever, household structure, particularly the presence and number of children, significantly influences the division of unpaid labor within families, and this, in turn, affects women’s economic opportunities and earnings. Women with dependent children face a much larger burden of unpaid care work compared to men, often restricting their ability to engage in paid labor and contributing to persistent wage gaps. The "motherhood penalty" is well-documented across various regions, where mothers, especially those with young children, experience reduced earnings compared to childless women and fathers with similar household characteristics. Studies show that mothers with dependent children earn significantly less than childless women. For instance, in the U.S., childless women earn about 93 cents to every dollar earned by childless men, but mothers with at least one child under 18 earn only 76 cents for every dollar earned by married fathers (Miller, 2020).

The number of children further exacerbates this imbalance. As the number of children increases, so does the time women spend on unpaid care and domestic work, reducing their availability for paid employment and reinforcing traditional gender roles. Research indicates that the presence of children not only increases the volume of unpaid work but also deepens the inequality in its distribution, as men generally do not proportionally increase their contributions to caregiving responsibilities (Craig & Mullan, 2011). Motherhood penalty has been found to vary across  income distribution, such that the wage penalty for mother hood is larger for low-income women than for their higher-income counterparts (Budig & Hodges (2010)). 

Employed mothers in the United States suffer a per‐child wage penalty of approximately 5%, on average, after controlling for the usual human capital and occupational factors that affect wages (Budig and England 2001; Anderson, Binder, and Krause 2003). Crittenden (2001)show that for those under the age of 35, the pay gap between mothers and nonmothers is larger than the pay gap between men and women. Research also shows that employed mothers are the group of women that now account for most of the “gender gap” in wages (Glass, 2004). Moorever, evidebce shos that individuals in households with children have less discretionary time and are thus more likely to be time poor than those in households without children. @Kalenkoski2011 show that controlling for other household characteristics, an additional child reduces a household adult's daily discretionary time by 35 minutes.



This uneven distribution of unpaid labor leads to a "care gap," which limits women's participation in the labor force and their career progression. Policies such as paid family leave, affordable childcare, and flexible work arrangements can help mitigate this disparity, but without significant changes in social norms around caregiving, the unequal burden of unpaid work remains a major barrier to gender equality in the labor market (Elson, 1999).

Several models explain the distribution of unpaid household work within couples. Three key theories are the time availability theory, resource-based theories, and gender ideology theory (@sub-shaaranAfrica report)

The time availability theory suggests that the partner with more paid employment spends less time on household work, as time is limited (Bianchi et al. 2000; Geist and Ruppanner 2018). Resource-based theories argue that financial resources create bargaining power, allowing the higher-earning partner to do less domestic work. As women’s earnings increase, they may also outsource tasks or invest in labor-saving devices (Gupta 2006). Gender ideology theory emphasizes that norms and values shape the division of labor, often leading women to do more housework despite earning more than their partners. This is explained by the concept of gender display, where women compensate for economic success by taking on more domestic tasks to align with traditional roles (Evertsson and Nermo 2004). However, Killewald and Gough (2010) found that while women’s housework decreases with earnings, this effect diminishes, showing that financial resources alone don’t equalize household labor.



Contribution/gap in the litearture


# Data and Methodology
We use a synthetic dataset that combines information from the American Time Use Survey (ATUS) and the Annual Social and Economic Supplements (ASEC) of the Current Population Survey (CPS) to first estimate the LIMTIP (). In this paper we use the dataset to invetsigate the impact of redistribution simulations on time-adjusted income poverty in addition to other time poverty indicators - time deficits, time poverty rate, hidden poverty. We use the dtaa for the period 2015-2019 which includes xx individuals xxx.

Our methods include making use of the LIMTIP framework (see Appendix aa). We then use simulations to calcuate the share of hh production in three different redistribution scenarios explained along with teh corresponding methodolgy below. 

# Conceptual framework
## Redistribution Scenarios
The idea of redistribution of household production responsibilities follows the principle that everyone in a household should be able to carry out their **fair** share of household work. But what constitutes a fair share? In this section, we present three different principles that could guide the redistribution of household production responsibilities among eligible household members. First, we use the simple egalitarianism principle that involves an equal division of total household production time among all working-age members. Second, we redistribute responsibilities based on the time available to household members. In the third scenario, redistribution is guided based on the principle of opportunity cost of time, where those with higher wages (higher opportunity cost of time) are assigned less household production time.

For all scenarios, we only consider the redistribution of required household production activities $R_j$ net of the portion met by household members that are either disabled or are not part of the working-age population. Thus, the goal is to simulate different $\alpha_{ij}$ values, which represent the share of required household production time that each household member takes on. We also impose the assumption that all household members are equally efficient at taking care of the household responsibilities. We outline the methods used for implementing the scenarios below.

## Scenario 1: Equal Shares

The first scenario considers the impact of redistributing household production such that all working-age members of the household are assigned an equal share of the required household production time. The new share is defined as:

$$\alpha_{ij}^E= \frac{1}{I_j}*(1-\alpha_{j}^{nw})
$$ {#eq-r1}

where $\alpha_{ij}^E$ represents the redistributed share of individual $i$; $I^j$ is the number of working-age persons in household $j$ and $\alpha_{j}^{nw}$ represents the total share of all non-working age household members. While this principle aligns with the idea of equality, it overlooks time equity by redistributing tasks without taking into consideration the time available to individuals.

## Scenario 2: Time Available

The time available scenario is based on the principles of equity. In contrast with Scenario 1, this one suggests that household responsibilities could be redistributed relative to the available time individuals may have after setting aside the time for personal maintenance requirements and income generation ($Z_{ij}=168-M-D_{ij}(L_{ij}+T_{ij})$).

To implement this, we first calculate the time available ($Z_{ij}$) for each individual and recalculate the shares $\alpha_{ij}^A$ using the ratio of time available to the total time available among working-age members. For individuals that do not have any time available ($Z_{ij}<0$), we set their $Z_{ij}$ to zero. This ensures that people who already suffer from time poverty are not assigned further tasks within the household. The new share is defined as:

$$
\begin{aligned}
Z_{ij} &=\max{\Big(168-M-D_{ij}(L_{ij}+T_{ij}-E_{ij}(S_{ij}),0\Big)} \\
\alpha_{ij}^A &= \frac{Z_{ij}}{\sum Z_{ij}} (1-\alpha_{j}^{nw})
\end{aligned}
$$ {#eq-r2}

Because there are individuals (young adults) who may still be in school, the standard definition of $Z_{ij}$ may not capture their true time availability. To address this, we add a correction to time availability for all individuals who declared attending school, subtracting from their available time ($Z_{ij}$) the average number of hours people spend in education activities per week ($S_{ij}$). This correction does not affect the time balance used for the identification of the time poor, only the estimation of time available and the adjusted shares $\alpha_{ij}^A$. 

## Scenario 3: Opportunity Cost

The third possibility is based on the idea of opportunity costs along marginalist lines. The sharing rule depends on the earning potentials of individuals, such that individuals with higher potential wages are assigned a lower share of household production time. In principle, this would encourage the most productive members of the household to spend more time in paid work, while those with lower earning potentials would take on more household production responsibilities.

For example, if there are only three working-age adults in a household, and where the second member earns twice as much as the first, and the third earns three times as much as the first, the shares of household production would be 1/2, 1/3, and 1/6 respectively. To implement this scenario, we first calculate the inverse of the wage of each individual $rw_{ij}$,  and then calculate the share of household production time as follows:

$$\begin{aligned}
rw_{ij} &= \frac{1}{w_{ij}} \\
\alpha_{ij}^O &= \frac{rw_{ij}}{\sum rw_{ij}} (1-\alpha_{j}^{nw})
\end{aligned}
$$ {#eq-r3}

where $w_{ij}$ is the wage of individual $i$.

Because we do not observe wage data for non-working household members, we use the potential/predicted wages for all working-age household members. To do this, we use a two-step procedure. First, we predict occupation and industry probabilities for all non-working individuals using a multinomial logit model. Second, we estimate a maximum likelihood Heckman selection model [@heckman1979] using the observed and predicted probabilities of belonging to specific occupations and industries, in addition to individual, household, and spouse demographic characteristics. With this information, we predict wages based on the model that corrects for sample selection and use those wages as proxies for the opportunity cost of time $w_{ij}$.


We look at the impact of the three redistribution scenarion on- i) Share of hh production; ii) time poverty; iii)time-adjusted income poverty; hidden poor ; xx;

In Appendix A, we present an overview of LIMTIP. 

!Move to appendix!
## LIMTIP: A New Measure of Time Poverty for the United States

Poverty is a multidimensional concept that goes beyond the simple notion of lack of income. In addition to income, poverty can be understood as a lack of access to resources, including time. The LIMTIP is a metric that, in addition to income poverty, incorporates aspects of time poverty that better capture the control households have over their resources. In this framework, time poverty refers to a scenario wherein people may not have any time left after engaging in activities that are essential for taking care of the household, its members, self-care, and paid work. At the household level, we consider an even more restrictive definition. Under the assumption that individuals with time surpluses are unable or unwilling to help those with time deficits, we consider a household to be time-poor if at least one member is time-poor.

As described in @policybrief_USLIMTIP and @wp_qmatch, the LIMTIP is built using a synthetic dataset that combines information from the American Time Use Survey (ATUS) and the Annual Social and Economic Supplements (ASEC) of the Current Population Survey (CPS). For the identification of time poverty, using weekly hours as the unit of analysis (168 hrs per week), we identify the amount of time individuals would have left ($X_{ij}$) after engaging in required activities for taking care of their share of responsibilities ($\alpha_{ij}$) in household production ($R_j$), personal maintenance ($M$), and paid work (commuting $T_{ij}$ and time spent at work $L_{ij}$). This is expressed in the following equation (see @eq-bal):

$$X_{ij} = 168 - M - \alpha_{ij}R_j-D_{ij}(L_{ij}+T_{ij})
$$ {#eq-bal}

The minimum time required for each of the components in @eq-bal are estimated using a mixture of assumptions, the synthetic dataset, and the ATUS dataset (see @wp_qmatch for details).
An individual is classified as time poor if they have a a negative time balance based on equation @eq-bal. 

At the household level, however, we assume that individuals with time surpluses are unable or unwilling to share and redistribute some of the responsibilities of those with time deficits. In this framework, a household is considered to be time-poor as long as there is atleast one person with a time deficit living in the household.[^2] This is expressed in the following equation (see @eq-hbal):

[^2]: To identify time poverty status, we only consider the time deficits of household members age 18 or older.

$$X_{j} = \sum_{i=1}^{I_j} \min(X_{ij},0)
$$ {#eq-hbal}

Once household time deficits $X_{j}$ are identified, we can adjust the official income poverty thresholds to account for the monetized value of the time deficits. For the U.S. case, we use a three-year average hourly wage for the industry private households obtained from Merged Outgoing Rotation Groups (MORG) to value the household time deficit. This value represents the amount of income that may be required to outsource some of the time responsibilities and eliminate time poverty. The adjusted poverty line is then calculated as:

$$Z_{j}^{adj} = Z_{j} + 52*P* |X_{j}|
$$ {#eq-limtip}

where $P$ is the price we use to give a monetary value to the time deficits the household ${j}$ faces, $Z_{j}$ is the official poverty line (SPM Poverty line), and $Z_{j}^{adj}$ is the adjusted poverty line. Intuitively, households that are not time-poor will not change status compared to the official poverty estimates. However, households that are time-poor could have their poverty status change if, after considering the adjusted poverty line, they fall below it. This group of households is considered to be the hidden poor.

In @tbl-limtip, we provide LIMTIP estimates for the U.S. using averages for the years 2005-2022. As the table shows, time poverty is a significant issue in the U.S., with 38.7% of individuals living in a time-poor household. Some individuals living in a non-poor household, however, may face other problems. As discussed in @policybrief_USLIMTIP, one of the drivers of individual time poverty is the time spent at work. In this framework, households may be non-time poor because few of their members may be working in the labor market, which in turn may also be reflected in the household's access to resources. This is also evident from @tbl-limtip, where the incidence of income poverty among people living in a non-time poor household is 17.8%, compared to 6% among those living in a time-poor household. 

It is also evident from @tbl-limtip that not everyone in a time-poor household is time-poor [recall that a housheold is classified as time poor, if atleast one member experiences time deficit]. In fact, only 52.1% of individuals living in a time-poor household are themselves time-poor. This suggests that there is potential for redistribution of household production responsibilities that could help reduce the incidence of time poverty if the time surpluses of some individuals could be used to help those with time deficits. 

Lastly, the table also shows the adjusted poverty rates (or LIMTIP Income poverty). As mentioned earlier, official poverty and LIMTIP income poverty do not change for non-time poor households. However, for time-poor households, the incidence of LIMTIP income poverty is 11.4%, compared to 5% for official poverty, which suggests that just over 6% of individuals in time-poor households are hidden poor.

 
:::{#tbl-limtip tbl-pos="H"}

\begin{tabular}{l c c c}
\toprule
            & \makecell{Time not-poor \\ Household} & \makecell{Time poor \\ Household} & Total\\
\hline
Share       &        61.3&        38.7 & 100 \\
SPM-Poverty &        17.8&         5.0 & \\
Ind Time Poverty&         0.0&        52.1 & \\
Adj Poverty/LIMTIP&        17.8&        11.4 & \\
\bottomrule
\end{tabular}

Poverty Rates by Household Time Poverty Status

:::


# Identifying the Problem {#sec-problem}

One of the strategies that could help reduce the problem of time poverty, the incidence of hidden poor, and mitrigate gender inequality is the redistribution of household production responsibilities across all working-age members in the household. At best, household members with time surpluses could take on more household responsibilities, reducing the burden of those with time deficits, and potentially lift the household out of poverty.  Even if the household remains time-poor, redistribution could still make the time deficits more equal among the household members, particulalry balancing the share between men and women.

For analysis we exclude the households that are not time-poor, because the goal of the current analysis is to evaluate the potential of redistribution to lift individuals and households out of time poverty while reducing the gender time-poverty gaps. While non-time poor households could potentially benefit from redistribution, reducing the gaps of time surpluses among household members and/or resulting in more gender-equitable sharing of household work, our focus in this paper id on time-poor households. 
While we allow for redistribution to happen across all working-age (18-64 years) and non-disabled household members (we call this group the elgible sample), our main focus is on analyzing the impact of redistribution between men and women. Thus, we will concentrate on exploring the impact of redistribution on heterosexual couples, where both partners are working-age, non-disabled individuals.

Under these considerations, we use an adaptation of the household classification proposed in @zacharias2021, with two main differences. First, we do not differentiate cases where, as described in @zacharias2021, time poverty is driven by employment. Second, for the household classification, we exclude the disabled when counting the number of members for whom redistribution is possible within a household. Thus, a "single" household refers to a household (SPM unit) where there is only 1 working-age, non-disabled household member. Under these considerations, @tbl-class provides the household classification used for the analysis.

:::{#tbl-class tbl-pos="H"}

| Household Type | Share | Description |
|-----|---|--------------|
| Non-Time Poor | 61.3% | Individuals living in households where no one is time-poor. |
| Single Person Elig | 5.1% | The household has only one working-age, non-disabled individual. Redistribution is not possible. |
| HH Type I | 1.4% | All members in the household are time-poor. Household poverty cannot be eliminated, but individual time poverty could change. |
| HH Type II | 5.2% | There is at least one non-time poor individual living in the household. Household poverty cannot be eliminated because total household time surplus is less than total household time deficit, however individual time poverty can be reduced. |
| HH Type III | 27.0% | There is at least one non-time poor individual living in the household. Household poverty can be eliminated because total household time surplus is greater than total housheold time deficit.|

Household Classification for Redistribution Analysis

:::

Across all these households, we will concentrate only on Households Type I, II and III, since redistribution could modify the time poverty status of individuals or households in these three categories. Among these, however, the main focus will be on HH Type III, where redistribution could potentially lift the household out of time poverty. In addition to this classification, we also consider if the individual is part of a couple or not. @tbl-class2 provides the individual time poverty rate [i.e share of time poor indiviudals in the household] across these categories.

:::{#tbl-class2 tbl-pos="H"}
 
\begin{tabular}{l*{4}{c}}
\hline\hline
            &  Disabled & Husband & Wife & Other \\
\hline
Non-Time Poor      &         - &         - &         - &         - \\
                   &       [8.1]&   [22.9]   &  [22.9]    &        [46.1] \\     
Single Person Elig &        12.1&        - &       - &        99.7 \\
                   &       [5.9]&        - &       - &        [94.1] \\
HH Type I          &         - &       100.0&       100.0&       100.0\\
                   &  [0.02]    &   [47.2] & [47.2] & [5.6] \\
HH Type II         &        37.3&        42.4&        58.7&        43.0\\
                   &     [0.02] &  [45.9] & [45.9] & [8.2] \\
HH Type III        &         5.9&        41.3&        58.2&        24.2\\
                   &  [1.0]      & [35.4] & [35.4] & [28.3] \\
\hline\hline
\end{tabular}

\footnotesize Note: The numbers in brackets represent the share of individuals who are disable, Husband or wife, or other, within a particular household type.

Individual Classification for Redistribution Analysis: Time Poverty Rate

:::

As shown in @tbl-class2, most of the individuals in the sample are in a couple relationship, thus part of our main sample of analysis. Other individuals, who may be part of a couple, but whose partner is either disabled or outside the working-age range, represent about 6% and 8% of households Type I and II, and 29% of households Type III. It is important to note that for individuals living in households Type II and III, the time poverty rate is higher among women (58%) compared to their partners (46%), reflecting the disproportionate burden of household production on women. Interestingly, other members in the household who are not part of the couple have a time poverty rate of 43% in HH type II, just above the rate of husbands, and 24.2% in HH Type III. This suggests that some of the redistribution would occur thanks to the help of these other members.



# Results
Overall results
Outcomes : share of hh production, time poverty, time deficits, limtip poor, transition rates, hh limtip and official poverty
Sub-groups: children, #children?; employment status; age groups?

# Policy Implication/Discussion 

# Conclusion

xx

# References {#sec-ref .unnumbered}

::: {#refs}
:::

 
